/*
-- ==========================================
-- Supabase Database DDL & RLS Setup SQL
-- ==========================================

-- 1. sessions 테이블 생성
CREATE TABLE sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pin_code VARCHAR(6) UNIQUE NOT NULL,
  target_distance NUMERIC NOT NULL DEFAULT 45,
  control_mode VARCHAR(20) NOT NULL DEFAULT 'BOTH',
  status VARCHAR(20) NOT NULL DEFAULT 'LOBBY',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. results 테이블 생성
CREATE TABLE results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_pin VARCHAR(6) REFERENCES sessions(pin_code) ON DELETE CASCADE,
  student_id VARCHAR(50) NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  selected_mass NUMERIC NOT NULL,
  selected_speed NUMERIC NOT NULL,
  actual_distance NUMERIC NOT NULL,
  offset_distance NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Row Level Security (RLS) 설정
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE results ENABLE ROW LEVEL SECURITY;

-- 모든 사용자(교사, 학생)가 세션 정보를 읽을 수 있도록 허용
CREATE POLICY "Allow public read sessions" ON sessions
  FOR SELECT TO anon USING (true);

-- 세션 생성 및 수정 권한
CREATE POLICY "Allow public insert sessions" ON sessions
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Allow public update sessions" ON sessions
  FOR UPDATE TO anon USING (true);

-- 결과 기록 읽기 권한
CREATE POLICY "Allow public read results" ON results
  FOR SELECT TO anon USING (true);

-- 결과 기록 쓰기 권한
CREATE POLICY "Allow public insert results" ON results
  FOR INSERT TO anon WITH CHECK (true);
*/

// --- 수파베이스 접속 정보 설정 ---
// ⚠️ 깃허브 배포 시 RLS를 테이블에 반드시 활성화하고 아래 정보를 본인의 수파베이스 정보로 채워 사용하세요.
const SUPABASE_URL = "https://vdyvpsteofvhbvvrilxe.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkeXZwc3Rlb2Z2aGJ2dnJpbHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1MzQ4ODMsImV4cCI6MjA5NTExMDg4M30.9kYsTmJGigMpanoj0CWFdHOZkDTUXqZo8neNuBxXIYU";

let supabaseClient = null;
// CDN으로 로드된 supabase 글로벌 객체를 사용하여 클라이언트를 빌드합니다.
if (typeof supabase !== 'undefined' && SUPABASE_URL && SUPABASE_ANON_KEY && SUPABASE_URL !== "YOUR_SUPABASE_URL") {
  supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
}

// --- 상태 및 상수 정의 ---
const F_BRAKE = 7716.05; // 고정 제동력 (Newton) - 500kg, 20km/h 일때 제동거리가 정확히 1m가 되도록 보정
const START_Z = -30;  // 차량 출발 위치 (m)
const BRAKE_Z = 0;    // 브레이크 시작 검은색 선 위치 (m)
const WHEEL_RADIUS = 0.6; // 바퀴 반지름 (m)

let scene, camera, renderer, controls;
let clock = new THREE.Clock();

// 차량 관련 객체
let truckGroup;
let wheels = [];
let cargoGroup;
let leftBrakeLight, rightBrakeLight;
let brakePointLight;

// 환경 객체
let redLineMesh;
let redLineSignpost;
let roadText;
let signboardMarkers = [];
let environmentGroup; // 환경 전체 메쉬를 담는 그룹 (다차선 재빌드용)

// 실시간 멀티플레이어 상태 변수
let userRole = null;          // 'teacher' | 'student' | null
let isMultiplayer = false;
let sessionPin = '';
let myNickname = '';
let myStudentId = null;
let students = [];            // 대기실에 들어온 학생 리스트 [{ id, nickname, is_ready }]
let activeStudents = [];      // 게임 중인 학생 리스트 (중간 접속/종료에 변하지 않도록 락 고정)
let studentReadyStates = {};  // studentId -> { mass, speed, isReady }
let studentCarPositions = {}; // studentId -> Z position
let studentCarSpeeds = {};    // studentId -> speed (mps)
let studentCarStates = {};    // studentId -> 'idle' | 'driving' | 'braking' | 'stopped'
let studentCarTimes = {};     // studentId -> elapsed time in braking
let studentResults = [];      // 최종 결과 랭킹 리스트
let controlMode = 'BOTH';     // 'BOTH' | 'MASS_ONLY' | 'SPEED_ONLY'
let fixedMass = 1500;
let fixedSpeed = 50;
let isDemoMode = false;       // 수파베이스 미연결 시 가상 교실 데모 모드로 작동하는 변수

let nameTagsContainer;
let studentDomElements = {};

// 교사용 35인 다차선 인스턴스 메쉬 객체들
let instancedChassis, instancedHood, instancedCab, instancedWheels, instancedFakeShadows, instancedCargo;

// 시뮬레이션 제어 변수
let simulationState = 'idle'; // 'idle', 'driving', 'braking', 'stopped'
let currentMode = 'challenge'; // 'challenge' 모드로 고정
let mass = 1500;             // kg
let initialSpeedKmh = 50;    // km/h
let currentSpeedMps = 0;     // m/s
let targetDistance = 45;     // m (챌린지 모드 목표 제동 거리)
let brakingElapsedTime = 0;  // 제동 경과 시간 (s)
let initialSpeedMps = 0;     // 제동 진입 시 실제 m/s

// 카메라 궤도 보간용 벡터
const offsetRear = new THREE.Vector3(-7, 4.5, -10); // 3/4 뒷모습 카메라 오프셋
const offsetSide = new THREE.Vector3(-14, 3.5, 3);  // 측면 카메라 오프셋

// --- 초기화 작업 ---
function init() {
  const container = document.getElementById('canvas-container');

  // 1. 씬 (Scene) 설정
  scene = new THREE.Scene();
  scene.background = new THREE.Color(0xbae1ff); // 밝고 청량한 하늘색
  scene.fog = new THREE.FogExp2(0xbae1ff, 0.0035); // 하늘빛 안개

  // 2. 카메라 (Camera) 설정
  camera = new THREE.PerspectiveCamera(45, container.clientWidth / container.clientHeight, 0.1, 1000);

  // 3. 렌더러 (Renderer) 설정
  renderer = new THREE.WebGLRenderer({ antialias: true });
  renderer.setSize(container.clientWidth, container.clientHeight);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.5)); // 성능 최적화: 초고해상도 기기에서 과다 픽셀 연산을 방지하기 위해 픽셀 레이쇼 상한을 2에서 1.5로 하향
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFShadowMap; // 성능 최적화: PCFSoftShadowMap 대신 연산 속도가 빠른 PCFShadowMap 적용
  container.appendChild(renderer.domElement);

  // 4. 마우스 컨트롤 (OrbitControls) 설정
  controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.dampingFactor = 0.05;
  controls.maxPolarAngle = Math.PI / 2 - 0.05; // 땅밑으로 카메라가 내려가지 않도록 차단
  controls.minDistance = 5;
  controls.maxDistance = 80;

  // 5. 조명 (Lighting)
  const ambientLight = new THREE.AmbientLight(0xe0f2fe, 0.9); // 밝은 주간 하늘색 앰비언트광
  scene.add(ambientLight);

  const sunLight = new THREE.DirectionalLight(0xffffff, 1.3); // 눈부신 백색 태양광
  sunLight.position.set(-30, 40, -10);
  sunLight.castShadow = true;
  sunLight.shadow.mapSize.set(1024, 1024); // 성능 최적화: 그림자 맵 해상도를 2048에서 1024로 하향 조정 (GPU 메모리 대역폭 감소)
  sunLight.shadow.camera.near = 0.5;
  sunLight.shadow.camera.far = 150;

  // 그림자 영역 조절 (픽업 트럭 이동 경로 커버)
  const d = 40;
  sunLight.shadow.camera.left = -d;
  sunLight.shadow.camera.right = d;
  sunLight.shadow.camera.top = d;
  sunLight.shadow.camera.bottom = -d;
  scene.add(sunLight);

  // 차량 제동 시 후미등 불빛을 바닥에 비추기 위한 포인트 라이트
  brakePointLight = new THREE.PointLight(0xff0000, 0, 10);
  scene.add(brakePointLight);

  // 환경 그룹 초기화 및 추가
  environmentGroup = new THREE.Group();
  scene.add(environmentGroup);

  // 학생 이름 꼬리표 컨테이너 추가
  nameTagsContainer = document.createElement('div');
  nameTagsContainer.id = 'student-names-container';
  nameTagsContainer.style.position = 'absolute';
  nameTagsContainer.style.top = '0';
  nameTagsContainer.style.left = '0';
  nameTagsContainer.style.width = '100%';
  nameTagsContainer.style.height = '100%';
  nameTagsContainer.style.pointerEvents = 'none';
  nameTagsContainer.style.zIndex = '15';
  nameTagsContainer.style.display = 'none';
  document.body.appendChild(nameTagsContainer);

  // 6. 도로 및 환경 생성 (초기값으로 1개 차선 생성)
  createEnvironment();

  // 7. 픽업 트럭 생성
  createPickupTruck();

  // 8. 카메라 초기 위치 설정
  resetCamera();

  // 9. UI 이벤트 리스너 등록
  setupUIEventListeners();

  // 10. 첫 챌린지 생성 및 초기화
  generateNewChallenge();

  // 11. 애니메이션 루프 시작
  window.addEventListener('resize', onWindowResize);
  renderer.setAnimationLoop(update);
}

// --- 환경 객체 생성 (도로, 가로등, 나무 등) ---
function createEnvironment() {
  rebuildEnvironment(1);
}

// --- 다차선 환경 재구성 (교사 다차선 모드 지원) ---
function rebuildEnvironment(numLanes = 1) {
  // 1. 기존 환경 메쉬 청소
  if (environmentGroup) {
    while (environmentGroup.children.length > 0) {
      const obj = environmentGroup.children[0];
      environmentGroup.remove(obj);
      // 메모리 관리: 지오메트리 및 재질 폐기
      if (obj.geometry) obj.geometry.dispose();
      if (obj.material) {
        if (Array.isArray(obj.material)) obj.material.forEach(m => m.dispose());
        else obj.material.dispose();
      }
    }
  }

  // 2. 도로 폭 계산 (1차선은 10m, 다차선은 차선당 3.5m + 좌우 갓길 4m)
  const roadWidth = numLanes === 1 ? 10 : numLanes * 3.5 + 4;
  const roadLength = 400;

  // 0. 넓은 초록색 잔디밭 지면
  const groundGeo = new THREE.PlaneGeometry(1000, 1000);
  const groundMat = new THREE.MeshStandardMaterial({
    color: 0x7da87b, // 차분하고 고급스러운 세이지-그린 잔디밭 톤
    roughness: 0.95,
    metalness: 0.1
  });
  const ground = new THREE.Mesh(groundGeo, groundMat);
  ground.rotation.x = -Math.PI / 2;
  ground.position.y = -0.02; // 도로 및 그리드와 Z-fighting(깜빡임) 방지
  ground.receiveShadow = true;
  environmentGroup.add(ground);

  // 1. 대형 바닥 그리드
  const gridHelper = new THREE.GridHelper(1000, 100, 0x648a61, 0x99bda8);
  gridHelper.position.y = -0.01;
  environmentGroup.add(gridHelper);

  // 2. 아스팔트 도로
  const roadGeo = new THREE.BoxGeometry(roadWidth, 0.1, roadLength);
  const roadMat = new THREE.MeshStandardMaterial({
    color: 0x2b323c, // 아스팔트 도로 색상 고정
    roughness: 0.85
  });
  const road = new THREE.Mesh(roadGeo, roadMat);
  road.position.set(0, -0.05, roadLength / 2 - 50); // Z: -50 ~ 350까지 연장
  road.receiveShadow = true;
  environmentGroup.add(road);

  // 3. 중앙 점선 및 갓길 실선
  const lineMat = new THREE.MeshBasicMaterial({ color: 0xffffff });
  const yellowLineMat = new THREE.MeshBasicMaterial({ color: 0xffd54f });

  // 좌우 황색 실선
  const leftLine = new THREE.Mesh(new THREE.PlaneGeometry(0.12, roadLength), yellowLineMat);
  leftLine.rotation.x = -Math.PI / 2;
  leftLine.position.set(-roadWidth / 2 + 0.3, 0.01, roadLength / 2 - 50);
  environmentGroup.add(leftLine);

  const rightLine = new THREE.Mesh(new THREE.PlaneGeometry(0.12, roadLength), yellowLineMat);
  rightLine.rotation.x = -Math.PI / 2;
  rightLine.position.set(roadWidth / 2 - 0.3, 0.01, roadLength / 2 - 50);
  environmentGroup.add(rightLine);

  // 차선 경계선 점선 그리기
  if (numLanes === 1) {
    // 단일 차선일 경우 중앙 점선 그리기
    for (let z = -50; z < 350; z += 8) {
      const dash = new THREE.Mesh(new THREE.PlaneGeometry(0.15, 4), lineMat);
      dash.rotation.x = -Math.PI / 2;
      dash.position.set(0, 0.01, z + 2);
      environmentGroup.add(dash);
    }
  } else {
    // 다차선일 경우 차선 경계선으로 점선 그리기
    for (let i = 1; i < numLanes; i++) {
      const laneX = - (numLanes * 3.5) / 2 + i * 3.5;
      for (let z = -50; z < 350; z += 8) {
        const dash = new THREE.Mesh(new THREE.PlaneGeometry(0.1, 4), lineMat);
        dash.rotation.x = -Math.PI / 2;
        dash.position.set(laneX, 0.01, z + 2);
        environmentGroup.add(dash);
      }
    }
  }

  // 4. 브레이크 시작선 (눈에 잘 띄는 네온 민트/시안색의 얇은 선)
  const brakeLineMat = new THREE.MeshStandardMaterial({
    color: 0x00e5ff,
    emissive: 0x00a3cc,
    emissiveIntensity: 0.8,
    roughness: 0.2
  });
  const brakeLine = new THREE.Mesh(new THREE.BoxGeometry(roadWidth, 0.02, 0.15), brakeLineMat);
  brakeLine.position.set(0, 0.01, BRAKE_Z);
  brakeLine.receiveShadow = true;
  environmentGroup.add(brakeLine);

  // 4.5. 도로 노면 위 "명인중학교 VR 실험실" 흰색 페인트 표식
  const roadTextTexture = createRoadTextTexture("명인중학교 VR 실험실");
  const roadTextGeo = new THREE.PlaneGeometry(40, 4.2); // Z축 길이 40m, 폭 4.2m
  const roadTextMat = new THREE.MeshBasicMaterial({
    map: roadTextTexture,
    transparent: true,
    depthWrite: false // 도로 노면에 자연스럽게 겹쳐지도록 Z-fighting 및 뎁스 버퍼 설정
  });
  roadText = new THREE.Mesh(roadTextGeo, roadTextMat);
  roadText.rotation.x = -Math.PI / 2;
  roadText.rotation.z = -Math.PI / 2; // 카메라 시점(측면 뷰)에서 똑바로 보이도록 기존 대비 180도 회전 설정

  // 단일 차선이면 좌측 편에, 다차선이면 중앙에 노출
  const textX = numLanes === 1 ? -2.8 : 0;
  roadText.position.set(textX, 0.012, targetDistance - 18.4);
  environmentGroup.add(roadText);

  // 브레이크선 옆에 세울 간판 (START)
  const startSign = createSignpost("START", 0xffffff, "#00e5ff");
  startSign.position.set(roadWidth / 2 + 1.5, 0, BRAKE_Z);
  environmentGroup.add(startSign);

  // 5. 목표 정지선 (빨간색 굵은 띠)
  const redLineMat = new THREE.MeshStandardMaterial({
    color: 0xff1744,
    emissive: 0xaa0012,
    emissiveIntensity: 0.5,
    roughness: 0.6
  });
  redLineMesh = new THREE.Mesh(new THREE.BoxGeometry(roadWidth, 0.02, 0.15), redLineMat);
  redLineMesh.position.set(0, 0.01, targetDistance);
  redLineMesh.receiveShadow = true;
  environmentGroup.add(redLineMesh);

  // 목표 정지선 옆에 세울 깃발/간판
  redLineSignpost = createSignpost("GOAL", 0xffffff, "#ff1744");
  redLineSignpost.position.set(roadWidth / 2 + 1.5, 0, targetDistance);
  environmentGroup.add(redLineSignpost);

  // 6. 10m 단위 거리 알림판 및 보조 가로선 배치
  signboardMarkers = [];
  for (let d = 10; d <= 200; d += 10) {
    const guideLine = new THREE.Mesh(new THREE.PlaneGeometry(roadWidth - 1, 0.05), new THREE.MeshBasicMaterial({ color: 0xcbd5e1 }));
    guideLine.rotation.x = -Math.PI / 2;
    guideLine.position.set(0, 0.005, d);
    environmentGroup.add(guideLine);

    const sign = createSignpost(`${d}m`, 0x94a3b8, "#475569", 0.7);
    sign.position.set(roadWidth / 2 + 1.2, 0, d);
    environmentGroup.add(sign);
    signboardMarkers.push({ mesh: sign, distance: d });
  }

  // 7. 가로등 (Street Lights) 배치
  for (let z = -30; z <= 240; z += 40) {
    createStreetLight(roadWidth / 2 + 0.8, z, false);
    createStreetLight(-roadWidth / 2 - 0.8, z + 20, true);
  }

  // 8. 로우폴리 나무 배치 (인스턴싱 적용으로 성능 향상)
  createInstancedTrees(roadWidth);
}

// --- 도로 노면 글씨 텍스처 생성 헬퍼 (고해상도 지원) ---
function createRoadTextTexture(text) {
  const canvas = document.createElement('canvas');
  canvas.width = 2048;
  canvas.height = 256;
  const ctx = canvas.getContext('2d');

  // 배경 투명화
  ctx.clearRect(0, 0, 2048, 256);

  // 글씨 스타일 정의 (선명한 도로 표지용 흰색)
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 110px "Noto Sans KR", sans-serif';
  ctx.textAlign = 'right'; // 우측 정렬로 변경하여 텍스트 끝이 평면 끝부분에 밀착되도록 설정
  ctx.textBaseline = 'middle';

  // 윤곽선을 주어 아스팔트 위에서 명확하게 보이도록 처리
  ctx.strokeStyle = 'rgba(0, 0, 0, 0.85)';
  ctx.lineWidth = 20;

  // 우측에 약간의 여백(80px)을 두고 그림
  const xPos = 2048 - 80;
  ctx.strokeText(text, xPos, 128);
  ctx.fillText(text, xPos, 128);

  return new THREE.CanvasTexture(canvas);
}

// --- 텍스트 표지판 생성 헬퍼 (캔버스 텍스처 사용) ---
function createSignpost(text, textColorHex, borderColorHex, scale = 1.0) {
  const group = new THREE.Group();

  // 지지대 쇠기둥
  const postGeo = new THREE.CylinderGeometry(0.06, 0.06, 2.2 * scale, 8);
  const postMat = new THREE.MeshStandardMaterial({ color: 0x475569, metalness: 0.8, roughness: 0.2 });
  const post = new THREE.Mesh(postGeo, postMat);
  post.position.y = (2.2 * scale) / 2;
  post.castShadow = true;
  group.add(post);

  // 표지판 뒷면 판데기
  const boardWidth = 1.6 * scale;
  const boardHeight = 0.9 * scale;
  const boardGeo = new THREE.BoxGeometry(boardWidth, boardHeight, 0.06);
  const boardMat = new THREE.MeshStandardMaterial({ color: 0x1e293b, roughness: 0.5 });
  const board = new THREE.Mesh(boardGeo, boardMat);
  board.position.y = (2.2 * scale) - (boardHeight / 2);
  board.castShadow = true;
  group.add(board);

  // 2D 캔버스로 글자 쓰기
  const canvas = document.createElement('canvas');
  canvas.width = 256;
  canvas.height = 128;
  const ctx = canvas.getContext('2d');

  // 내부 어두운 배경 채우기
  ctx.fillStyle = 'rgba(15, 23, 42, 0.95)';
  ctx.fillRect(0, 0, 256, 128);

  // 테두리 선
  ctx.strokeStyle = borderColorHex;
  ctx.lineWidth = 8;
  ctx.strokeRect(4, 4, 248, 120);

  // 텍스트 그리기
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 44px "Outfit", "Noto Sans KR", sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(text, 128, 64);

  const texture = new THREE.CanvasTexture(canvas);
  const labelGeo = new THREE.PlaneGeometry(boardWidth - 0.05, boardHeight - 0.05);
  const labelMat = new THREE.MeshBasicMaterial({ map: texture, transparent: true });

  // 앞뒤로 글씨판 붙이기 (회전해서 볼 수 있게)
  const labelFront = new THREE.Mesh(labelGeo, labelMat);
  labelFront.position.set(0, board.position.y, 0.035);
  group.add(labelFront);

  const labelBack = new THREE.Mesh(labelGeo, labelMat);
  labelBack.position.set(0, board.position.y, -0.035);
  labelBack.rotation.y = Math.PI;
  group.add(labelBack);

  return group;
}

// --- 가로등 생성 헬퍼 ---
function createStreetLight(x, z, rotateLeft = false) {
  const group = new THREE.Group();
  group.position.set(x, 0, z);

  // 기둥
  const poleHeight = 6.0;
  const poleGeo = new THREE.CylinderGeometry(0.08, 0.14, poleHeight, 8);
  const poleMat = new THREE.MeshStandardMaterial({ color: 0x334155, metalness: 0.8, roughness: 0.3 });
  const pole = new THREE.Mesh(poleGeo, poleMat);
  pole.position.y = poleHeight / 2;
  pole.castShadow = true;
  group.add(pole);

  // 수평 암(Arm)
  const armLength = 2.0;
  const armGeo = new THREE.CylinderGeometry(0.05, 0.05, armLength, 8);
  const arm = new THREE.Mesh(armGeo, poleMat);
  arm.rotation.z = Math.PI / 2;
  arm.position.set(rotateLeft ? -armLength / 2 : armLength / 2, poleHeight, 0);
  group.add(arm);

  // 램프 헤드
  const headGeo = new THREE.BoxGeometry(0.6, 0.15, 0.4);
  const headMat = new THREE.MeshStandardMaterial({ color: 0x1e293b });
  const head = new THREE.Mesh(headGeo, headMat);
  head.position.set(rotateLeft ? -armLength : armLength, poleHeight - 0.05, 0);
  group.add(head);

  // 가로등 발광 부위
  const lightSourceGeo = new THREE.BoxGeometry(0.5, 0.02, 0.3);
  const lightSourceMat = new THREE.MeshBasicMaterial({ color: 0xfffee6 }); // 은은한 웜화이트
  const lightSource = new THREE.Mesh(lightSourceGeo, lightSourceMat);
  lightSource.position.set(rotateLeft ? -armLength : armLength, poleHeight - 0.13, 0);
  group.add(lightSource);

  environmentGroup.add(group);
}

// --- 로우폴리 나무 인스턴싱 생성 헬퍼 (THREE.InstancedMesh 적용) ---
function createInstancedTrees(currentRoadWidth = 10) {
  const roadWidth = currentRoadWidth;
  const treePositions = [];

  // 1. 나무들의 개별 위치와 스케일, 나뭇잎 색상을 먼저 무작위 생성하여 배열에 저장
  for (let z = -60; z < 300; z += 15) {
    const heightScaleL = 0.8 + Math.random() * 0.5;
    const xL = -roadWidth / 2 - 3 - Math.random() * 4;
    const zL = z + (Math.random() - 0.5) * 5;
    const leavesColors = [0x2e7d32, 0x388e3c, 0x4caf50];
    const colorL = new THREE.Color(leavesColors[Math.floor(Math.random() * leavesColors.length)]);

    treePositions.push({ x: xL, y: 0, z: zL, scale: heightScaleL, color: colorL });

    const heightScaleR = 0.8 + Math.random() * 0.5;
    const xR = roadWidth / 2 + 3 + Math.random() * 4;
    const zR = z + (Math.random() - 0.5) * 5;
    const colorR = new THREE.Color(leavesColors[Math.floor(Math.random() * leavesColors.length)]);

    treePositions.push({ x: xR, y: 0, z: zR, scale: heightScaleR, color: colorR });
  }

  const count = treePositions.length;

  // 2. Trunk (나무 기둥) InstancedMesh 생성
  // base geometry의 피벗을 아래에 맞추기 위해 실린더를 Y 방향으로 0.5 이동한 뒤 geometry를 만듭니다.
  const baseTrunkGeo = new THREE.CylinderGeometry(0.12, 0.18, 1.0, 8);
  baseTrunkGeo.translate(0, 0.5, 0);

  const trunkMat = new THREE.MeshStandardMaterial({ color: 0x5c4033, roughness: 0.9 });
  const trunkInstancedMesh = new THREE.InstancedMesh(baseTrunkGeo, trunkMat, count);
  trunkInstancedMesh.castShadow = true;
  trunkInstancedMesh.receiveShadow = true;

  // 3. Leaves (나뭇잎) InstancedMesh 생성
  // 나뭇잎은 나무당 3단 콘이므로 총 개수는 count * 3
  // ConeGeometry(1.0, 1.0, 7)을 베이스로 하고 피벗을 아래에 맞추기 위해 Y 방향으로 0.5 이동
  const baseLeavesGeo = new THREE.ConeGeometry(1.0, 1.0, 7);
  baseLeavesGeo.translate(0, 0.5, 0);

  const leavesMat = new THREE.MeshStandardMaterial({
    roughness: 0.9,
    flatShading: true
  });
  const leavesInstancedMesh = new THREE.InstancedMesh(baseLeavesGeo, leavesMat, count * 3);
  leavesInstancedMesh.castShadow = true;
  leavesInstancedMesh.receiveShadow = true;

  const dummy = new THREE.Object3D();

  // 4. 인스턴스 행렬 및 색상 업데이트
  for (let i = 0; i < count; i++) {
    const tree = treePositions[i];
    const trunkHeight = 1.0 * tree.scale;

    // 기둥 매트릭스 설정 (피벗이 바닥이므로 Y축 척도를 trunkHeight로 직접 지정)
    dummy.position.set(tree.x, tree.y, tree.z);
    dummy.rotation.set(0, 0, 0);
    dummy.scale.set(1, trunkHeight, 1);
    dummy.updateMatrix();
    trunkInstancedMesh.setMatrixAt(i, dummy.matrix);

    // 나뭇잎 3단 콘 매트릭스 설정
    for (let layer = 0; layer < 3; layer++) {
      const coneRadius = (0.9 - layer * 0.2) * tree.scale;
      const coneHeight = (1.1 - layer * 0.1) * tree.scale;
      const coneY = trunkHeight + (layer * 0.7 * tree.scale);

      dummy.position.set(tree.x, tree.y + coneY, tree.z);
      dummy.rotation.set(0, 0, 0);
      dummy.scale.set(coneRadius, coneHeight, coneRadius);
      dummy.updateMatrix();

      const leafIndex = i * 3 + layer;
      leavesInstancedMesh.setMatrixAt(leafIndex, dummy.matrix);
      leavesInstancedMesh.setColorAt(leafIndex, tree.color);
    }
  }

  // 업데이트 완료 노티파이
  trunkInstancedMesh.instanceMatrix.needsUpdate = true;
  leavesInstancedMesh.instanceMatrix.needsUpdate = true;
  if (leavesInstancedMesh.instanceColor) {
    leavesInstancedMesh.instanceColor.needsUpdate = true;
  }

  environmentGroup.add(trunkInstancedMesh);
  environmentGroup.add(leavesInstancedMesh);
}


// ==========================================================================
// 실시간 멀티플레이어 통신 및 교실 게임 로직 (Supabase Realtime)
// ==========================================================================

let realtimeChannel = null;

// --- 역할 선택 처리 ---
function selectRole(role) {
  userRole = role;
  isMultiplayer = true;
  document.getElementById('role-overlay').style.display = 'none';
  document.getElementById('main-ui').style.display = 'grid';

  if (role === 'teacher') {
    document.getElementById('teacher-panel').style.display = 'flex';
    document.getElementById('student-panel').style.display = 'none';

    // 기본 싱글 플레이용 차량 숨김
    if (truckGroup) truckGroup.visible = false;

    initTeacherSession();
  } else {
    document.getElementById('teacher-panel').style.display = 'none';
    document.getElementById('student-panel').style.display = 'flex';
    document.getElementById('student-login-overlay').style.display = 'flex';

    // 로그인 완료 전까지 메인 제어 잠금
    document.getElementById('main-ui').style.pointerEvents = 'none';
  }
}
window.selectRole = selectRole;

// --- 교사용 세션 생성 및 초기화 ---
async function initTeacherSession() {
  const DEFAULT_PIN = "802935";
  sessionPin = DEFAULT_PIN;

  if (!supabaseClient) {
    alert("수파베이스가 연결되지 않았습니다. app.js에서 SUPABASE_URL 및 SUPABASE_ANON_KEY를 설정해 주세요.");
    return;
  }

  try {
    // 1. 기존 동일 고정 PIN의 세션 삭제 (중복 오류 예방 및 데이터 초기 청소)
    // 외래 키 ON DELETE CASCADE 설정으로 인해 results 테이블 데이터도 연쇄 삭제됩니다.
    await supabaseClient
      .from('sessions')
      .delete()
      .eq('pin_code', DEFAULT_PIN);

    // 2. 기본 고정 PIN으로 새 세션 등록 시도 (status: LOBBY)
    const { error } = await supabaseClient
      .from('sessions')
      .insert([{
        pin_code: sessionPin,
        target_distance: targetDistance,
        control_mode: 'BOTH',
        status: 'LOBBY'
      }]);

    if (error) {
      console.warn("기본 핀코드('802935') 등록 중복 또는 에러로 난수 핀코드로 우회합니다:", error);
      // Fallback: 6자리 난수 PIN 번호 생성
      sessionPin = Math.floor(100000 + Math.random() * 900000).toString();
      const fallbackRes = await supabaseClient
        .from('sessions')
        .insert([{
          pin_code: sessionPin,
          target_distance: targetDistance,
          control_mode: 'BOTH',
          status: 'LOBBY'
        }]);
      if (fallbackRes.error) throw fallbackRes.error;
    }

    document.getElementById('teacher-pin-value').innerText = sessionPin;

    // 3. 실시간 채널 구독 및 Presence 연결
    setupTeacherRealtime();

    // 초기 제어 모드 설정 및 슬라이더 가동 범위 초기 세팅
    setControlMode('BOTH');

  } catch (err) {
    console.error("수파베이스 세션 등록 실패:", err);
    alert("수파베이스 세션 등록에 실패했습니다. DB 테이블(sessions, results)이 생성되어 있는지 확인하세요.");
  }
}

// --- 교사용 실시간 소켓/Presence 바인딩 ---
function setupTeacherRealtime() {
  realtimeChannel = supabaseClient.channel(`room_${sessionPin}`, {
    config: { presence: { key: sessionPin } }
  });

  realtimeChannel
    .on('presence', { event: 'sync' }, () => {
      // 대기실 실시간 접속 학생 동기화
      const state = realtimeChannel.presenceState();
      students = [];
      Object.keys(state).forEach(key => {
        state[key].forEach(p => {
          if (p.role === 'student') {
            students.push({ id: p.id, nickname: p.nickname });
          }
        });
      });
      updateStudentLobbyUI();
    })
    .on('broadcast', { event: 'student-ready' }, ({ payload }) => {
      // 학생의 슬라이더 조작 준비 완료 상태 수신
      studentReadyStates[payload.studentId] = {
        mass: payload.mass,
        speed: payload.speed,
        isReady: payload.isReady
      };
      updateTeacherReadyStatus();
    })
    .on('broadcast', { event: 'student-result' }, ({ payload }) => {
      // 학생 개별 제동 완료 정보 수신 (실시간 리더보드 반영)
      addStudentResult(payload);
    })
    .subscribe(async (status) => {
      if (status === 'SUBSCRIBED') {
        // 교사로 접속 정보 트래킹
        await realtimeChannel.track({ role: 'teacher', id: 'teacher' });
      }
    });
}

// --- 교사 대기실 참여 학생 명단 갱신 ---
function updateStudentLobbyUI() {
  const container = document.getElementById('student-list-container');
  const countSpan = document.getElementById('connected-count');

  countSpan.innerText = students.length;
  container.innerHTML = '';

  if (students.length === 0) {
    container.innerHTML = '<p class="empty-list-msg">학생 접속 대기 중...</p>';
    return;
  }

  students.forEach(student => {
    const isReady = studentReadyStates[student.id]?.isReady || false;
    const tag = document.createElement('div');
    tag.className = `student-tag ${isReady ? 'ready' : ''}`;
    tag.innerHTML = `<span class="status-dot"></span>${student.nickname}`;
    container.appendChild(tag);
  });
}

// --- 교사용 목표 거리 입력 동기화 ---
function updateTeacherTargetDist(val) {
  targetDistance = parseFloat(val);
  const label = document.getElementById('teacher-target-val-label');
  if (label) label.innerText = `${targetDistance.toFixed(1)}m`;

  // 빨간선 위치 동기화
  if (redLineMesh) {
    redLineMesh.position.z = targetDistance;
    redLineSignpost.position.set(5 + 1.5, 0, targetDistance);
    if (roadText) roadText.position.z = targetDistance - 18.4;
  }
}
window.updateTeacherTargetDist = updateTeacherTargetDist;

// --- 교사용 학생 조작 모드 지정 시 슬라이더 범위 동적 제한 ---
function updateTeacherTargetSliderRange(mode) {
  const slider = document.getElementById('teacher-target-distance');
  const minLabel = document.getElementById('teacher-target-min-label');
  const maxLabel = document.getElementById('teacher-target-max-label');
  
  if (!slider) return;

  let minVal = 25;
  let maxVal = 95;
  let stepVal = 1;

  if (mode === 'MASS_ONLY') {
    // 속도 50km/h 고정, 질량 1000 ~ 5000kg
    // d_min = 1000 * 50^2 / 200000 = 12.5m
    // d_max = 5000 * 50^2 / 200000 = 62.5m
    minVal = 12.5;
    maxVal = 62.5;
    stepVal = 0.5;
  } else if (mode === 'SPEED_ONLY') {
    // 질량 1500kg 고정, 속도 10 ~ 150km/h
    // d_min = 1500 * 10^2 / 200000 = 0.75m
    // d_max = 1500 * 150^2 / 200000 = 168.75m
    minVal = 0.75;
    maxVal = 168.75;
    stepVal = 0.05;
  } else {
    minVal = 25;
    maxVal = 95;
    stepVal = 1;
  }

  slider.min = minVal;
  slider.max = maxVal;
  slider.step = stepVal;

  if (minLabel) minLabel.innerText = `${minVal.toFixed(1)}m`;
  if (maxLabel) maxLabel.innerText = `${maxVal.toFixed(1)}m`;

  const rangeGuide = document.getElementById('teacher-range-guide');
  if (rangeGuide) {
    rangeGuide.innerText = `도달 가능 범위: ${minVal.toFixed(1)}m ~ ${maxVal.toFixed(1)}m`;
  }

  // 현재 설정된 targetDistance가 새로운 범위를 벗어날 경우 클램핑
  if (targetDistance < minVal) {
    targetDistance = minVal;
  } else if (targetDistance > maxVal) {
    targetDistance = maxVal;
  }

  slider.value = targetDistance;
  updateTeacherTargetDist(targetDistance);
}

// --- 교사용 학생 조작 모드 지정 ---
function setControlMode(mode) {
  controlMode = mode;
  document.querySelectorAll('.mode-btn').forEach(btn => btn.classList.remove('active'));

  let guideText = '';
  if (mode === 'BOTH') {
    document.getElementById('mode-btn-both').classList.add('active');
    guideText = '학생들이 질량과 속력을 모두 자유롭게 변경할 수 있습니다.';
  } else if (mode === 'MASS_ONLY') {
    document.getElementById('mode-btn-mass').classList.add('active');
    guideText = '속력이 50 km/h로 잠기며, 학생들이 차량 질량만 변경할 수 있습니다. (설정 가능 거리: 12.5m ~ 62.5m)';
  } else if (mode === 'SPEED_ONLY') {
    document.getElementById('mode-btn-speed').classList.add('active');
    guideText = '질량이 1500 kg으로 잠기며, 학생들이 초기 속력만 변경할 수 있습니다. (설정 가능 거리: 0.75m ~ 168.75m)';
  }
  const guideEl = document.getElementById('mode-guide-text');
  if (guideEl) guideEl.innerText = guideText;

  updateTeacherTargetSliderRange(mode);
}
window.setControlMode = setControlMode;

// --- 교사용 실험 조건 고정 (준비 단계 진입) ---
async function lockSessionSettings() {
  activeStudents = [...students];

  const lobbyEl = document.getElementById('teacher-lobby');
  if (lobbyEl) lobbyEl.style.display = 'none';
  const activeEl = document.getElementById('teacher-active');
  if (activeEl) activeEl.style.display = 'flex';

  // 활성화 조건 공시
  const targetDistEl = document.getElementById('active-target-dist');
  if (targetDistEl) targetDistEl.innerText = `${targetDistance}m`;
  let modeLabel = '질량+속력';
  if (controlMode === 'MASS_ONLY') modeLabel = '질량만 조작';
  if (controlMode === 'SPEED_ONLY') modeLabel = '속력만 조작';
  const modeEl = document.getElementById('active-control-mode');
  if (modeEl) modeEl.innerText = modeLabel;

  // 인스턴스 3D 트럭 및 도로 재건축
  rebuildEnvironment(activeStudents.length || 1);
  setupTeacherInstancedTrucks(activeStudents.length || 1);

  // 모든 학생의 차량 위치 초기화
  studentCarPositions = {};
  studentCarSpeeds = {};
  studentCarStates = {};
  studentCarTimes = {};
  activeStudents.forEach(s => {
    studentCarPositions[s.id] = START_Z;
    studentCarSpeeds[s.id] = 0;
    studentCarStates[s.id] = 'idle';
  });
  updateInstancedTrucks();

  // 학생들에게 조건 동기화 전송
  const payload = {
    targetDistance,
    controlMode,
    fixedMass: 1500,
    fixedSpeed: 50
  };

  if (supabaseClient && realtimeChannel) {
    // 1. DB 세션 정보 고정
    await supabaseClient
      .from('sessions')
      .update({
        target_distance: targetDistance,
        control_mode: controlMode,
        status: 'READY'
      })
      .eq('pin_code', sessionPin);

    // 2. 브로드캐스트로 락 시나리오 전송
    realtimeChannel.send({
      type: 'broadcast',
      event: 'lock-settings',
      payload
    });
  }

  updateTeacherReadyStatus();

  // 데모 모드일 때 모의 학생 준비 완료 시뮬레이션
  if (isDemoMode) {
    activeStudents.forEach((s, i) => {
      setTimeout(() => {
        studentReadyStates[s.id] = {
          mass: 1000 + Math.floor(Math.random() * 17) * 250, // 1000 ~ 5000kg
          speed: 20 + Math.floor(Math.random() * 12) * 10,   // 20 ~ 130km/h
          isReady: true
        };
        updateTeacherReadyStatus();
      }, 1000 + i * 800);
    });
  }
}
window.lockSessionSettings = lockSessionSettings;

// --- 교사용 조건 해제 (다시 대기실로) ---
async function unlockSessionSettings() {
  const activeEl = document.getElementById('teacher-active');
  if (activeEl) activeEl.style.display = 'none';
  const lobbyEl = document.getElementById('teacher-lobby');
  if (lobbyEl) lobbyEl.style.display = 'flex';

  // 준비 상태 리셋
  students.forEach(s => {
    if (studentReadyStates[s.id]) {
      studentReadyStates[s.id].isReady = false;
    }
  });
  updateStudentLobbyUI();

  if (supabaseClient && realtimeChannel) {
    await supabaseClient
      .from('sessions')
      .update({ status: 'LOBBY' })
      .eq('pin_code', sessionPin);

    realtimeChannel.send({
      type: 'broadcast',
      event: 'unlock-settings'
    });
  }
}
window.unlockSessionSettings = unlockSessionSettings;

// --- 교사용 준비 상태 집계 갱신 ---
function updateTeacherReadyStatus() {
  const readyFraction = document.getElementById('ready-fraction');
  const progressBar = document.getElementById('ready-progress-bar');
  const startBtn = document.getElementById('btn-teacher-start');

  const total = activeStudents.length;
  let readyCount = 0;
  activeStudents.forEach(s => {
    if (studentReadyStates[s.id]?.isReady) readyCount++;
  });

  if (readyFraction) readyFraction.innerText = `${readyCount} / ${total}`;
  const percent = total > 0 ? (readyCount / total) * 100 : 0;
  if (progressBar) progressBar.style.width = `${percent}%`;

  // 학생이 최소 1명 이상 있으면 일괄 출발 버튼을 활성화하여 교사가 강제 출발할 수 있도록 허용
  if (startBtn) {
    if (total > 0) {
      startBtn.disabled = false;
      if (readyCount === total) {
        startBtn.innerHTML = `<svg class="icon" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>🚀 일괄 출발 (전원 완료)`;
        startBtn.className = 'btn btn-primary';
      } else {
        startBtn.innerHTML = `<svg class="icon" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>🚀 강제 출발 (${readyCount}/${total}명 완료)`;
        startBtn.className = 'btn btn-accent';
      }
    } else {
      startBtn.disabled = true;
      startBtn.innerHTML = `<svg class="icon" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>일괄 출발 (대기 중)`;
      startBtn.className = 'btn btn-primary';
    }
  }
}

// --- 교사용 일괄 출발 트리거 ---
async function triggerLaunchAll() {
  const startBtn = document.getElementById('btn-teacher-start');
  if (startBtn) startBtn.disabled = true;
  simulationState = 'driving';

  // 각 학생 차량 주행 기초 세팅
  activeStudents.forEach(s => {
    const state = studentReadyStates[s.id] || { mass: 1500, speed: 50 };
    studentCarPositions[s.id] = START_Z;
    studentCarSpeeds[s.id] = state.speed / 3.6; // m/s
    studentCarStates[s.id] = 'driving';
    studentCarTimes[s.id] = 0;
  });

  studentResults = []; // 리더보드 비우기

  if (supabaseClient && realtimeChannel) {
    // 1. DB 세션 상태 주행중(PLAYING) 변경
    await supabaseClient
      .from('sessions')
      .update({ status: 'PLAYING' })
      .eq('pin_code', sessionPin);

    // 2. 출발 브로드캐스트 전송
    realtimeChannel.send({
      type: 'broadcast',
      event: 'launch'
    });
  }
}
window.triggerLaunchAll = triggerLaunchAll;

// --- 학생용 세션 PIN 참가 신청 ---
function joinSession() {
  const pinInput = document.getElementById('student-pin');
  const nickInput = document.getElementById('student-nickname');

  sessionPin = pinInput.value.trim();
  myNickname = nickInput.value.trim();

  if (sessionPin.length !== 6) {
    alert("접속 PIN 번호 6자리를 정확히 입력해 주세요.");
    return;
  }
  if (!myNickname) {
    alert("이름을 입력해 주세요.");
    return;
  }

  if (!supabaseClient) {
    alert("수파베이스가 연결되지 않았습니다. app.js에서 SUPABASE_URL 및 SUPABASE_ANON_KEY를 설정해 주세요.");
    return;
  }

  // 수파베이스 접속 시도
  setupStudentRealtime();
}
window.joinSession = joinSession;

// --- 학생용 실시간 채널 연결 ---
function setupStudentRealtime() {
  realtimeChannel = supabaseClient.channel(`room_${sessionPin}`);

  realtimeChannel
    .on('broadcast', { event: 'lock-settings' }, ({ payload }) => {
      // 교사가 조건을 잠갔을 때 작동
      onTeacherLockSettings(payload);
    })
    .on('broadcast', { event: 'unlock-settings' }, () => {
      // 교사가 조건을 풀었을 때 다시 로비 대기로
      showStudentLobbyWait();
    })
    .on('broadcast', { event: 'launch' }, () => {
      // 교사의 일괄 출발 발송 수신
      onLaunchTriggered();
    })
    .on('broadcast', { event: 'next-round' }, () => {
      // 다음 라운드 준비 리셋
      onNextRoundTriggered();
    })
    .subscribe(async (status) => {
      if (status === 'SUBSCRIBED') {
        myStudentId = 'student_' + Math.random().toString(36).substring(2, 9);

        // Presence로 학생 정보 트래킹 등록
        await realtimeChannel.track({
          role: 'student',
          id: myStudentId,
          nickname: myNickname
        });

        document.getElementById('student-login-overlay').style.display = 'none';
        document.getElementById('main-ui').style.pointerEvents = 'auto';
        showStudentLobbyWait();
      } else if (status === 'CHANNEL_ERROR') {
        alert("서버 연결 오류가 발생했습니다. PIN 번호를 확인해 주세요.");
      }
    });
}

// --- 학생 대기 스크린 출력 ---
function showStudentLobbyWait() {
  document.getElementById('student-wait-message').style.display = 'flex';
  document.getElementById('student-dashboard').style.display = 'none';
}

// --- 교사의 조건 고정 수신 시 대시보드 렌더링 ---
function onTeacherLockSettings(config) {
  const waitMsg = document.getElementById('student-wait-message');
  if (waitMsg) waitMsg.style.display = 'none';
  const dashboard = document.getElementById('student-dashboard');
  if (dashboard) dashboard.style.display = 'flex';

  targetDistance = config.targetDistance;
  controlMode = config.controlMode;
  fixedMass = config.fixedMass;
  fixedSpeed = config.fixedSpeed;

  const targetDisplay = document.getElementById('student-target-display');
  if (targetDisplay) targetDisplay.innerText = `${targetDistance.toFixed(1)}m`;

  const massSlider = document.getElementById('mass-slider');
  const massInput = document.getElementById('mass-input');
  const speedSlider = document.getElementById('speed-slider');
  const speedInput = document.getElementById('speed-input');

  const massGroup = document.getElementById('student-mass-group');
  const speedGroup = document.getElementById('student-speed-group');

  // RLS 및 조건 잠금 상태 동기화 및 입력 활성화/비활성화 처리
  if (controlMode === 'MASS_ONLY') {
    if (speedSlider) {
      speedSlider.value = fixedSpeed;
      speedSlider.disabled = true;
    }
    if (speedInput) {
      speedInput.value = fixedSpeed;
      speedInput.disabled = true;
    }
    initialSpeedKmh = fixedSpeed;

    if (massSlider) massSlider.disabled = false;
    if (massInput) massInput.disabled = false;

    if (speedGroup) speedGroup.classList.add('locked');
    if (massGroup) massGroup.classList.remove('locked');
  }
  else if (controlMode === 'SPEED_ONLY') {
    if (massSlider) {
      massSlider.value = fixedMass;
      massSlider.disabled = true;
    }
    if (massInput) {
      massInput.value = fixedMass;
      massInput.disabled = true;
    }
    mass = fixedMass;
    updateCargoBoxes(mass);

    if (speedSlider) speedSlider.disabled = false;
    if (speedInput) speedInput.disabled = false;

    if (massGroup) massGroup.classList.add('locked');
    if (speedGroup) speedGroup.classList.remove('locked');
  }
  else {
    if (massSlider) massSlider.disabled = false;
    if (massInput) massInput.disabled = false;
    if (speedSlider) speedSlider.disabled = false;
    if (speedInput) speedInput.disabled = false;

    if (massGroup) massGroup.classList.remove('locked');
    if (speedGroup) speedGroup.classList.remove('locked');
  }

  // 대시보드 업데이트
  updateDashboard();

  // 준비 완료 버튼 활성화
  const readyBtn = document.getElementById('btn-student-ready');
  if (readyBtn) {
    readyBtn.disabled = false;
    readyBtn.className = 'btn btn-primary';
    readyBtn.innerText = '👍 준비 완료 (Ready)';
  }
  const statusText = document.getElementById('student-status-text');
  if (statusText) statusText.style.display = 'none';
}

// --- 학생용 준비 완료 토글 ---
function toggleStudentReady() {
  const readyBtn = document.getElementById('btn-student-ready');
  const isReadyNow = !readyBtn.classList.contains('btn-success');

  if (isReadyNow) {
    readyBtn.className = 'btn btn-success';
    readyBtn.innerText = '✅ 준비 완료됨';
    document.getElementById('student-status-text').style.display = 'block';

    // 슬라이더 잠금
    document.getElementById('mass-slider').disabled = true;
    document.getElementById('mass-input').disabled = true;
    document.getElementById('speed-slider').disabled = true;
    document.getElementById('speed-input').disabled = true;
  } else {
    readyBtn.className = 'btn btn-primary';
    readyBtn.innerText = '👍 준비 완료 (Ready)';
    document.getElementById('student-status-text').style.display = 'none';

    // 슬라이더 해제
    if (controlMode !== 'SPEED_ONLY') {
      document.getElementById('mass-slider').disabled = false;
      document.getElementById('mass-input').disabled = false;
    }
    if (controlMode !== 'MASS_ONLY') {
      document.getElementById('speed-slider').disabled = false;
      document.getElementById('speed-input').disabled = false;
    }
  }

  const payload = {
    studentId: myStudentId,
    mass: mass,
    speed: initialSpeedKmh,
    isReady: isReadyNow
  };

  // 교사 및 소켓에게 전달
  if (supabaseClient && realtimeChannel) {
    realtimeChannel.send({
      type: 'broadcast',
      event: 'student-ready',
      payload
    });
  } else {
    // 데모 로컬 시뮬레이션용 직접 변수 수정
    studentReadyStates[myStudentId] = payload;
    updateTeacherReadyStatus();
  }
}
window.toggleStudentReady = toggleStudentReady;

// --- 교사 출발 신호 수신에 따른 주행 런칭 ---
function onLaunchTriggered() {
  // 모달 닫기
  closeStudentResultModal();
  document.getElementById('btn-student-ready').disabled = true;

  // 로컬 시뮬레이션 상태 구동 시작
  simulationState = 'driving';
  initialSpeedMps = initialSpeedKmh / 3.6;
  currentSpeedMps = initialSpeedMps;
  brakingElapsedTime = 0;

  if (truckGroup) {
    truckGroup.position.set(0, 0, START_Z);
  }
}

// --- 학생 제동 종료 결과 서버 보고 및 UI 피드백 ---
function reportStudentResult(actual, offset) {
  const payload = {
    studentId: myStudentId,
    nickname: myNickname,
    mass: mass,
    speed: initialSpeedKmh,
    actualDistance: actual,
    offsetDistance: offset
  };

  if (supabaseClient && realtimeChannel) {
    // 1. 소켓 브로드캐스트 보고 (리더보드 우선 업데이트)
    realtimeChannel.send({
      type: 'broadcast',
      event: 'student-result',
      payload
    });

    // 2. DB 레코드 안전 기록 (배후 저장)
    recordResultToDB(payload);
  } else {
    // 데모 모드
    addStudentResult(payload);
  }

  // 학생 개인 성적표 모달 렌더링
  showStudentResultDetail(actual, offset);
}

// --- DB 결과 삽입 보조함수 ---
async function recordResultToDB(payload) {
  try {
    // RLSAnon 권한을 이용해 본인의 세션 및 닉네임 기준 결과 기록
    await supabaseClient
      .from('results')
      .insert([{
        session_pin: sessionPin,
        student_id: myStudentId,
        nickname: myNickname,
        selected_mass: payload.mass,
        selected_speed: payload.speed,
        actual_distance: payload.actualDistance,
        offset_distance: payload.offsetDistance
      }]);
  } catch (err) {
    console.warn("결과 DB 저장 보조 에러:", err);
  }
}

// --- 학생용 성적표 모달 노출 ---
function showStudentResultDetail(actual, offset) {
  const modal = document.getElementById('student-result-modal');
  const actualText = document.getElementById('student-actual-dist');
  const targetText = document.getElementById('student-target-dist-result');
  const offsetText = document.getElementById('student-offset-dist');
  const feedbackBox = document.getElementById('student-result-feedback');

  if (actualText) actualText.innerText = `${actual.toFixed(2)}m`;
  if (targetText) targetText.innerText = `${targetDistance.toFixed(1)}m`;

  const absDiff = Math.abs(offset);
  if (offsetText) {
    const sign = offset >= 0 ? '+' : '';
    offsetText.innerText = `${sign}${offset.toFixed(2)}m`;
    if (absDiff <= 0.6) {
      offsetText.style.color = '#4caf50'; // 성공 시 연두색
    } else {
      offsetText.style.color = '#ff1744'; // 실패 시 빨간색
    }
  }

  if (feedbackBox) {
    if (absDiff <= 0.6) {
      feedbackBox.className = 'result-feedback-box success';
      feedbackBox.innerHTML = `🏆 <strong>축하합니다!</strong> 오차 <strong>${absDiff.toFixed(2)}m</strong> 이내로 <strong>정확히 정차</strong>하여 미션을 해결했습니다!`;
    } else {
      feedbackBox.className = 'result-feedback-box fail';
      let tip = '';
      if (controlMode === 'MASS_ONLY') {
        if (offset > 0) {
          tip = `<br><span style="font-size:0.8rem; color:#ff8a80; display:block; margin-top:8px; font-weight:500;">💡 과학 팁: 질량(m)이 감소하면 운동에너지가 작아져 제동 거리가 줄어듭니다. 질량을 더 낮춰 보세요!</span>`;
        } else {
          tip = `<br><span style="font-size:0.8rem; color:#ff8a80; display:block; margin-top:8px; font-weight:500;">💡 과학 팁: 질량(m)이 증가하면 운동에너지가 커져 제동 거리가 늘어납니다. 질량을 더 높여 보세요!</span>`;
        }
      } else if (controlMode === 'SPEED_ONLY') {
        if (offset > 0) {
          tip = `<br><span style="font-size:0.8rem; color:#ff8a80; display:block; margin-top:8px; font-weight:500;">💡 과학 팁: 초기 속력(v)이 느려지면 제동 거리가 제곱 비례하여 줄어듭니다. 속력을 더 낮춰 보세요!</span>`;
        } else {
          tip = `<br><span style="font-size:0.8rem; color:#ff8a80; display:block; margin-top:8px; font-weight:500;">💡 과학 팁: 초기 속력(v)이 빨라지면 제동 거리가 제곱 비례하여 늘어납니다. 속력을 더 높여 보세요!</span>`;
        }
      } else {
        if (offset > 0) {
          tip = `<br><span style="font-size:0.8rem; color:#ff8a80; display:block; margin-top:8px; font-weight:500;">💡 과학 팁: 질량을 낮추거나 속력을 줄여서 운동에너지를 감소시켜 보세요!</span>`;
        } else {
          tip = `<br><span style="font-size:0.8rem; color:#ff8a80; display:block; margin-top:8px; font-weight:500;">💡 과학 팁: 질량을 높이거나 속력을 늘려서 운동에너지를 증가시켜 보세요!</span>`;
        }
      }

      if (offset > 0) {
        feedbackBox.innerHTML = `💥 <strong>정지선 초과!</strong> 목표 지점을 <strong>${offset.toFixed(2)}m 오버런</strong>했습니다.${tip}`;
      } else {
        feedbackBox.innerHTML = `⚠️ <strong>제동거리 미달!</strong> 목표선에 <strong>${absDiff.toFixed(2)}m 도달하지 못하고</strong> 정차했습니다.${tip}`;
      }
    }
  }

  if (modal) modal.style.display = 'flex';
}

function closeStudentResultModal() {
  const modal = document.getElementById('student-result-modal');
  if (modal) modal.style.display = 'none';
}
window.closeStudentResultModal = closeStudentResultModal;

// --- 교사용 리더보드 결과 누적 처리 ---
function addStudentResult(res) {
  // 중복 삽입 방지
  if (studentResults.some(r => r.studentId === res.studentId)) return;

  studentResults.push(res);

  // 오차 절댓값이 작은 순서대로 정렬 (오름차순)
  studentResults.sort((a, b) => Math.abs(a.offsetDistance) - Math.abs(b.offsetDistance));

  // 리더보드 렌더링
  updateLeaderboardUI();
}

// --- 교사용 리더보드 테이블 UI 렌더링 ---
function updateLeaderboardUI() {
  const tbody = document.getElementById('leaderboard-rows');
  tbody.innerHTML = '';

  studentResults.forEach((res, index) => {
    const tr = document.createElement('tr');

    // 상위 3위 색상 배지 지정
    const rank = index + 1;
    if (rank === 1) tr.className = 'rank-1';
    else if (rank === 2) tr.className = 'rank-2';
    else if (rank === 3) tr.className = 'rank-3';

    let rankLabel = `${rank}위`;
    if (rank === 1) rankLabel = '🥇 1위';
    else if (rank === 2) rankLabel = '🥈 2위';
    else if (rank === 3) rankLabel = '🥉 3위';

    // 조작 모드에 따라 설정값 명시
    const setValues = `${res.mass}kg, ${res.speed}km/h`;

    tr.innerHTML = `
      <td class="badge-cell">${rankLabel}</td>
      <td style="font-weight:700;">${res.nickname}</td>
      <td>${setValues}</td>
      <td>${res.actualDistance.toFixed(2)}m</td>
      <td><span style="font-weight:700;">${res.offsetDistance >= 0 ? '+' : ''}${res.offsetDistance.toFixed(2)}m</span></td>
    `;
    tbody.appendChild(tr);
  });
}

// --- 교사용 다음 라운드 준비 (대기 리셋) ---
async function resetForNextRound() {
  document.getElementById('teacher-leaderboard-section').style.display = 'none';
  document.getElementById('teacher-lobby').style.display = 'flex';

  // 준비 상태 초기화
  students.forEach(s => {
    if (studentReadyStates[s.id]) {
      studentReadyStates[s.id].isReady = false;
    }
  });
  studentResults = [];
  updateStudentLobbyUI();

  // 새로운 목표 생성 활성화
  simulationState = 'idle';

  if (supabaseClient && realtimeChannel) {
    await supabaseClient
      .from('sessions')
      .update({ status: 'LOBBY' })
      .eq('pin_code', sessionPin);

    realtimeChannel.send({
      type: 'broadcast',
      event: 'next-round'
    });
  }

  // 데모 모드일 때 모의 학생 접속 대기
  if (isDemoMode) {
    // 준비 상태 초기화로 lobby 리셋
  }
}
window.resetForNextRound = resetForNextRound;

// --- 학생용 다음 라운드 진입 동기화 수신 ---
function onNextRoundTriggered() {
  closeStudentResultModal();
  simulationState = 'idle';

  // 슬라이더 잠금 해제 및 준비상태 해제
  const readyBtn = document.getElementById('btn-student-ready');
  readyBtn.className = 'btn btn-primary';
  readyBtn.innerText = '👍 준비 완료 (Ready)';
  document.getElementById('student-status-text').style.display = 'none';

  if (controlMode !== 'SPEED_ONLY') {
    document.getElementById('mass-slider').disabled = false;
    document.getElementById('mass-input').disabled = false;
  }
  if (controlMode !== 'MASS_ONLY') {
    document.getElementById('speed-slider').disabled = false;
    document.getElementById('speed-input').disabled = false;
  }

  // 대기실 전환
  showStudentLobbyWait();
}

// --- 교사용 35인 다차선 가상 데모 지원 트리거 ---
let mockRaceTimer = null;
function startDemoLobby() {
  // 데모 모드 제거
}

// --- 교사용 다차선 도로에 맞춰 인스턴스 3D 생성 ---
function setupTeacherInstancedTrucks(count) {
  // 기존 기하가 겹치지 않도록 청소
  if (instancedChassis) scene.remove(instancedChassis);
  if (instancedHood) scene.remove(instancedHood);
  if (instancedCab) scene.remove(instancedCab);
  if (instancedWheels) scene.remove(instancedWheels);
  if (instancedFakeShadows) scene.remove(instancedFakeShadows);
  if (instancedCargo) scene.remove(instancedCargo);

  const chassisGeo = new THREE.BoxGeometry(2.3, 0.3, 5.2);
  const chassisMat = new THREE.MeshStandardMaterial({ color: 0x1e293b, metalness: 0.8, roughness: 0.4 });
  instancedChassis = new THREE.InstancedMesh(chassisGeo, chassisMat, count);
  instancedChassis.castShadow = false; // 성능 최적화: 동적 그림자 제외
  instancedChassis.receiveShadow = false;
  scene.add(instancedChassis);

  const hoodGeo = new THREE.BoxGeometry(2.1, 0.75, 1.4);
  const bodyPaintMat = new THREE.MeshStandardMaterial({ metalness: 0.8, roughness: 0.2 }); // 색상은 인스턴스별 지정 예정
  instancedHood = new THREE.InstancedMesh(hoodGeo, bodyPaintMat, count);
  instancedHood.castShadow = false;
  instancedHood.receiveShadow = false;
  scene.add(instancedHood);

  const cabGeo = new THREE.BoxGeometry(2.0, 1.0, 1.8);
  instancedCab = new THREE.InstancedMesh(cabGeo, bodyPaintMat, count);
  instancedCab.castShadow = false;
  instancedCab.receiveShadow = false;
  scene.add(instancedCab);

  const tireGeo = new THREE.CylinderGeometry(WHEEL_RADIUS, WHEEL_RADIUS, 0.45, 16); // 바퀴 기하 간소화
  const tireMat = new THREE.MeshStandardMaterial({ color: 0x18181b, roughness: 0.85 });
  instancedWheels = new THREE.InstancedMesh(tireGeo, tireMat, count * 4);
  instancedWheels.castShadow = false;
  instancedWheels.receiveShadow = false;
  scene.add(instancedWheels);

  // Fake Shadow 가짜그림자 (2D 판데기)
  const shadowGeo = new THREE.PlaneGeometry(1, 1);
  const shadowMat = new THREE.MeshBasicMaterial({
    color: 0x000000,
    transparent: true,
    opacity: 0.3,
    depthWrite: false
  });
  instancedFakeShadows = new THREE.InstancedMesh(shadowGeo, shadowMat, count);
  scene.add(instancedFakeShadows);

  // Cargo boxes
  const boxSize = 0.45;
  const boxGeo = new THREE.BoxGeometry(boxSize, boxSize, boxSize);
  const boxMat = new THREE.MeshStandardMaterial({ color: 0xcd853f, roughness: 0.9 });
  instancedCargo = new THREE.InstancedMesh(boxGeo, boxMat, count * 16);
  instancedCargo.castShadow = false;
  instancedCargo.receiveShadow = false;
  scene.add(instancedCargo);

  // 인스턴스별 고유 차량 컬러 맵핑 (학생별 시인성 부여)
  const colors = [0x00a8ff, 0xff1744, 0x00e676, 0xffea00, 0xd500f9, 0xff6d00, 0x00e5ff, 0xf50057];
  for (let i = 0; i < count; i++) {
    const color = new THREE.Color(colors[i % colors.length]);
    instancedChassis.setColorAt(i, color);
    instancedHood.setColorAt(i, color);
    instancedCab.setColorAt(i, color);
  }

  if (instancedChassis.instanceColor) instancedChassis.instanceColor.needsUpdate = true;
  if (instancedHood.instanceColor) instancedHood.instanceColor.needsUpdate = true;
  if (instancedCab.instanceColor) instancedCab.instanceColor.needsUpdate = true;

  // 꼬리표 DOM 생성
  if (nameTagsContainer) nameTagsContainer.innerHTML = '';
  studentDomElements = {};
  activeStudents.forEach((student, index) => {
    const tag = document.createElement('div');
    tag.innerText = student.nickname;

    // 스타일 주입
    tag.style.position = 'absolute';
    tag.style.transform = 'translate(-50%, -100%)';
    const hexColor = colors[index % colors.length].toString(16).padStart(6, '0');
    tag.style.background = 'rgba(18, 22, 33, 0.92)';
    tag.style.border = `2px solid #${hexColor}`;
    tag.style.borderRadius = '20px';
    tag.style.padding = '4px 12px';
    tag.style.color = '#ffffff';
    tag.style.fontSize = '12px';
    tag.style.fontWeight = 'bold';
    tag.style.whiteSpace = 'nowrap';
    tag.style.boxShadow = '0 4px 15px rgba(0,0,0,0.5)';
    tag.style.pointerEvents = 'none';
    tag.style.display = 'none';

    if (nameTagsContainer) nameTagsContainer.appendChild(tag);
    studentDomElements[student.id] = tag;
  });
}

// --- 차선 번호 맵핑 헬퍼 ---
function getLaneX(index, total) {
  if (total <= 1) return 0;
  const laneWidth = 3.5;
  return - (total - 1) * laneWidth / 2 + index * laneWidth;
}

// --- 교사용 인스턴스 3D 업데이트 루프 ---
function updateInstancedTrucks() {
  if (!instancedChassis) return;

  const dummy = new THREE.Object3D();
  let boxIndex = 0;

  activeStudents.forEach((student, index) => {
    const zPos = studentCarPositions[student.id] !== undefined ? studentCarPositions[student.id] : START_Z;
    const xPos = getLaneX(index, activeStudents.length);

    // 1. Chassis
    dummy.position.set(xPos, 0.45, zPos);
    dummy.rotation.set(0, 0, 0);
    dummy.scale.set(1, 1, 1);
    dummy.updateMatrix();
    instancedChassis.setMatrixAt(index, dummy.matrix);

    // 2. Hood
    dummy.position.set(xPos, 0.45 + 0.15 + 0.375, zPos + 1.8);
    dummy.rotation.set(0, 0, 0);
    dummy.scale.set(1, 1, 1);
    dummy.updateMatrix();
    instancedHood.setMatrixAt(index, dummy.matrix);

    // 3. Cab
    dummy.position.set(xPos, 0.45 + 0.15 + 0.5, zPos + 0.3);
    dummy.rotation.set(0, 0, 0);
    dummy.scale.set(1, 1, 1);
    dummy.updateMatrix();
    instancedCab.setMatrixAt(index, dummy.matrix);

    // 4. Wheels
    const distanceTravelled = zPos - START_Z;
    const rotationAngle = distanceTravelled / WHEEL_RADIUS;

    const wheelOffsets = [
      { x: -1.15, z: 1.5 },
      { x: 1.15, z: 1.5 },
      { x: -1.15, z: -1.6 },
      { x: 1.15, z: -1.6 }
    ];

    wheelOffsets.forEach((offset, wIdx) => {
      dummy.position.set(xPos + offset.x, 0.35, zPos + offset.z);
      dummy.rotation.set(rotationAngle, 0, Math.PI / 2);
      dummy.scale.set(1, 1, 1);
      dummy.updateMatrix();
      instancedWheels.setMatrixAt(index * 4 + wIdx, dummy.matrix);
    });

    // 5. 가짜 그림자
    dummy.position.set(xPos, 0.012, zPos + 0.1);
    dummy.rotation.set(-Math.PI / 2, 0, 0);
    dummy.scale.set(2.4, 5.4, 1); // 트럭 하단 가로/세로 매칭
    dummy.updateMatrix();
    instancedFakeShadows.setMatrixAt(index, dummy.matrix);

    // 6. 상자 짐
    const state = studentReadyStates[student.id] || { mass: 1500 };
    const addedWeight = state.mass - 1000;
    const numBoxes = Math.min(16, Math.floor(addedWeight / 250));

    const boxSize = 0.45;
    const boxSlots = [];
    for (let layer = 0; layer < 2; layer++) {
      const yOffset = 0.7 + (boxSize / 2) + layer * (boxSize + 0.02);
      for (let col = 0; col < 4; col++) {
        const zOffset = -1.9 + 0.9 - col * 0.6;
        for (let row = 0; row < 2; row++) {
          const xOffset = -0.45 + row * 0.9;
          boxSlots.push({ x: xOffset, y: yOffset, z: zOffset });
        }
      }
    }

    for (let bIdx = 0; bIdx < 16; bIdx++) {
      if (bIdx < numBoxes) {
        const slot = boxSlots[bIdx];
        dummy.position.set(xPos + slot.x, slot.y, zPos + slot.z);
        dummy.rotation.set(0, 0, 0);
        dummy.scale.set(1, 1, 1);
        dummy.updateMatrix();
        instancedCargo.setMatrixAt(boxIndex, dummy.matrix);
      } else {
        // 불필요한 박스는 크기를 0으로 숨김
        dummy.position.set(0, -999, 0);
        dummy.scale.set(0, 0, 0);
        dummy.updateMatrix();
        instancedCargo.setMatrixAt(boxIndex, dummy.matrix);
      }
      boxIndex++;
    }
  });

  instancedChassis.instanceMatrix.needsUpdate = true;
  instancedHood.instanceMatrix.needsUpdate = true;
  instancedCab.instanceMatrix.needsUpdate = true;
  instancedWheels.instanceMatrix.needsUpdate = true;
  instancedFakeShadows.instanceMatrix.needsUpdate = true;
  instancedCargo.instanceMatrix.needsUpdate = true;
}

// --- 교사용 학생 이름표 2D 캔버스 오버레이 갱신 ---
function updateStudentNameTags() {
  if (userRole !== 'teacher' || simulationState === 'idle' || !nameTagsContainer) {
    if (nameTagsContainer) nameTagsContainer.style.display = 'none';
    return;
  }
  nameTagsContainer.style.display = 'block';

  const widthHalf = renderer.domElement.clientWidth / 2;
  const heightHalf = renderer.domElement.clientHeight / 2;
  const tempV = new THREE.Vector3();

  activeStudents.forEach((student, index) => {
    const domEl = studentDomElements[student.id];
    if (!domEl) return;

    const zPos = studentCarPositions[student.id] !== undefined ? studentCarPositions[student.id] : START_Z;
    const xPos = getLaneX(index, activeStudents.length);

    tempV.set(xPos, 2.8, zPos);
    tempV.project(camera);

    // 카메라 뒷쪽에 있는 태그는 숨김
    if (tempV.z > 1) {
      domEl.style.display = 'none';
      return;
    }

    const x = (tempV.x * widthHalf) + widthHalf;
    const y = -(tempV.y * heightHalf) + heightHalf;

    domEl.style.display = 'block';
    domEl.style.left = `${x}px`;
    domEl.style.top = `${y}px`;
  });
}


// --- 3D 픽업 트럭 제작 (기하학 구조 결합) ---
function createPickupTruck() {
  truckGroup = new THREE.Group();

  // 1. 차체 섀시 (어두운 금속 바닥)
  const chassisGeo = new THREE.BoxGeometry(2.3, 0.3, 5.2);
  const chassisMat = new THREE.MeshStandardMaterial({ color: 0x1e293b, metalness: 0.8, roughness: 0.4 });
  const chassis = new THREE.Mesh(chassisGeo, chassisMat);
  chassis.position.y = 0.45;
  chassis.castShadow = true;
  chassis.receiveShadow = true;
  truckGroup.add(chassis);

  // 2. 엔진 보닛 (앞코)
  const hoodGeo = new THREE.BoxGeometry(2.1, 0.75, 1.4);
  const bodyPaintMat = new THREE.MeshStandardMaterial({
    color: 0x00a8ff, // 메탈릭 브라이트 블루
    metalness: 0.8,
    roughness: 0.2
  });
  const hood = new THREE.Mesh(hoodGeo, bodyPaintMat);
  hood.position.set(0, 0.45 + 0.15 + 0.375, 1.8);
  hood.castShadow = true;
  hood.receiveShadow = true;
  truckGroup.add(hood);

  // 3. 운전석 캐빈 (Cab)
  const cabGeo = new THREE.BoxGeometry(2.0, 1.0, 1.8);
  const cab = new THREE.Mesh(cabGeo, bodyPaintMat);
  cab.position.set(0, 0.45 + 0.15 + 0.5, 0.3);
  cab.castShadow = true;
  cab.receiveShadow = true;
  truckGroup.add(cab);

  // 유리창 (유광 블랙 검정색 바)
  const glassMat = new THREE.MeshStandardMaterial({ color: 0x0d0f12, roughness: 0.1, metalness: 0.9 });

  // 앞 유리창 (살짝 기울어짐 연출을 위해 전면에 플레이트 삽입)
  const frontWindshield = new THREE.Mesh(new THREE.PlaneGeometry(1.8, 0.7), glassMat);
  frontWindshield.position.set(0, 1.2, 1.21);
  frontWindshield.rotation.x = -Math.PI / 10;
  truckGroup.add(frontWindshield);

  // 옆면 창문들
  const leftWindow = new THREE.Mesh(new THREE.PlaneGeometry(1.4, 0.55), glassMat);
  leftWindow.position.set(-1.01, 1.15, 0.3);
  leftWindow.rotation.y = -Math.PI / 2;
  truckGroup.add(leftWindow);

  const rightWindow = new THREE.Mesh(new THREE.PlaneGeometry(1.4, 0.55), glassMat);
  rightWindow.position.set(1.01, 1.15, 0.3);
  rightWindow.rotation.y = Math.PI / 2;
  truckGroup.add(rightWindow);

  // 뒷창문
  const backWindow = new THREE.Mesh(new THREE.PlaneGeometry(1.5, 0.5), glassMat);
  backWindow.position.set(0, 1.15, -0.61);
  truckGroup.add(backWindow);

  // 3.5. 제동 위치 기준 데칼 (양옆 노란색 화살표 페인트 - 지면 밀착형 포인터)
  const arrowShape = new THREE.Shape();
  arrowShape.moveTo(-0.02, 0.40); // 얇은 깃대 시작
  arrowShape.lineTo(0.02, 0.40);
  arrowShape.lineTo(0.02, 0.0);
  arrowShape.lineTo(0.10, 0.0);   // 화살촉 날개
  arrowShape.lineTo(0, -0.15);    // 지면을 향한 화살촉 끝부분
  arrowShape.lineTo(-0.10, 0.0);
  arrowShape.lineTo(-0.02, 0.0);
  arrowShape.closePath();

  const arrowGeo = new THREE.ShapeGeometry(arrowShape);
  const arrowMat = new THREE.MeshStandardMaterial({
    color: 0xffd600, // 선명한 노란색
    roughness: 0.4,
    metalness: 0.1
  });

  // 우측 도어 화살표 (앞코 우측 - 지면 정렬선)
  const rightArrow = new THREE.Mesh(arrowGeo, arrowMat);
  rightArrow.position.set(1.065, 0.18, 2.45); // 앞 범퍼 Z=2.45에 배치, y=0.18로 맞춰 끝단이 지면 위 0.03m에 오도록 함
  rightArrow.rotation.y = Math.PI / 2;
  truckGroup.add(rightArrow);

  // 좌측 도어 화살표 (앞코 좌측 - 지면 정렬선)
  const leftArrow = new THREE.Mesh(arrowGeo, arrowMat);
  leftArrow.position.set(-1.065, 0.18, 2.45); // 앞 범퍼 Z=2.45에 배치, y=0.18로 맞춰 끝단이 지면 위 0.03m에 오도록 함
  leftArrow.rotation.y = -Math.PI / 2;
  truckGroup.add(leftArrow);

  // 4. 전면 그릴 및 헤드라이트
  const grillGeo = new THREE.BoxGeometry(1.8, 0.4, 0.1);
  const grillMat = new THREE.MeshStandardMaterial({ color: 0x111622, metalness: 0.9, roughness: 0.1 });
  const grill = new THREE.Mesh(grillGeo, grillMat);
  grill.position.set(0, 0.85, 2.51);
  truckGroup.add(grill);

  // 헤드라이트 (발광 옐로우)
  const headlightGeo = new THREE.BoxGeometry(0.3, 0.2, 0.05);
  const headlightMat = new THREE.MeshBasicMaterial({ color: 0xfffacd });

  const leftHeadlight = new THREE.Mesh(headlightGeo, headlightMat);
  leftHeadlight.position.set(-0.85, 0.9, 2.53);
  truckGroup.add(leftHeadlight);

  const rightHeadlight = new THREE.Mesh(headlightGeo, headlightMat);
  rightHeadlight.position.set(0.85, 0.9, 2.53);
  truckGroup.add(rightHeadlight);

  // 5. 트럭 적재함 (Cargo Bed) 울타리 형태
  const bedWallMat = bodyPaintMat;

  // 바닥판
  const bedFloor = new THREE.Mesh(new THREE.BoxGeometry(2.1, 0.1, 2.6), new THREE.MeshStandardMaterial({ color: 0x334155, roughness: 0.7 }));
  bedFloor.position.set(0, 0.65, -1.9);
  bedFloor.receiveShadow = true;
  truckGroup.add(bedFloor);

  // 적재함 좌측 벽
  const leftWall = new THREE.Mesh(new THREE.BoxGeometry(0.1, 0.7, 2.6), bedWallMat);
  leftWall.position.set(-1.0, 0.95, -1.9);
  leftWall.castShadow = true;
  leftWall.receiveShadow = true;
  truckGroup.add(leftWall);

  // 적재함 우측 벽
  const rightWall = new THREE.Mesh(new THREE.BoxGeometry(0.1, 0.7, 2.6), bedWallMat);
  rightWall.position.set(1.0, 0.95, -1.9);
  rightWall.castShadow = true;
  rightWall.receiveShadow = true;
  truckGroup.add(rightWall);

  // 적재함 후면 문 (Tailgate)
  const tailGate = new THREE.Mesh(new THREE.BoxGeometry(2.0, 0.7, 0.1), bedWallMat);
  tailGate.position.set(0, 0.95, -3.2);
  tailGate.castShadow = true;
  tailGate.receiveShadow = true;
  truckGroup.add(tailGate);

  // 6. 후미 브레이크등 (Brake Lights)
  const brakeLightGeo = new THREE.BoxGeometry(0.2, 0.25, 0.05);
  // 초기 상태는 어두운 붉은색
  const initialBrakeLightMat = new THREE.MeshStandardMaterial({
    color: 0x3a0000,
    emissive: 0x000000,
    roughness: 0.3
  });

  leftBrakeLight = new THREE.Mesh(brakeLightGeo, initialBrakeLightMat.clone());
  leftBrakeLight.position.set(-0.85, 0.95, -3.26);
  truckGroup.add(leftBrakeLight);

  rightBrakeLight = new THREE.Mesh(brakeLightGeo, initialBrakeLightMat.clone());
  rightBrakeLight.position.set(0.85, 0.95, -3.26);
  truckGroup.add(rightBrakeLight);

  // 7. 4개의 바퀴 (Wheels) 장착
  const wheelPositions = [
    { x: -1.15, y: 0.35, z: 1.5, isLeft: true },  // 앞왼바퀴
    { x: 1.15, y: 0.35, z: 1.5, isLeft: false }, // 앞오른바퀴
    { x: -1.15, y: 0.35, z: -1.6, isLeft: true }, // 뒤왼바퀴
    { x: 1.15, y: 0.35, z: -1.6, isLeft: false } // 뒤오른바퀴
  ];

  const tireGeo = new THREE.CylinderGeometry(WHEEL_RADIUS, WHEEL_RADIUS, 0.45, 24);
  const tireMat = new THREE.MeshStandardMaterial({ color: 0x18181b, roughness: 0.85 });
  const rimMat = new THREE.MeshStandardMaterial({ color: 0xd1d5db, metalness: 0.8, roughness: 0.2 });

  wheelPositions.forEach((pos) => {
    const wheelGroup = new THREE.Group();
    wheelGroup.position.set(pos.x, pos.y, pos.z);

    // 타이어 고무
    const tire = new THREE.Mesh(tireGeo, tireMat);
    tire.rotation.z = Math.PI / 2;
    tire.castShadow = true;
    wheelGroup.add(tire);

    // 휠 림 (중앙 은색 허브)
    const rim = new THREE.Mesh(new THREE.CylinderGeometry(0.35, 0.35, 0.47, 16), rimMat);
    rim.rotation.z = Math.PI / 2;
    wheelGroup.add(rim);

    // 휠 스포크 (회전을 확실히 시각적으로 인지할 수 있도록 스포크 디자인 추가)
    const spoke1 = new THREE.Mesh(new THREE.BoxGeometry(0.08, 0.65, 0.08), rimMat);
    spoke1.position.x = pos.isLeft ? -0.24 : 0.24;
    wheelGroup.add(spoke1);

    const spoke2 = new THREE.Mesh(new THREE.BoxGeometry(0.08, 0.08, 0.65), rimMat);
    spoke2.position.x = pos.isLeft ? -0.24 : 0.24;
    wheelGroup.add(spoke2);

    truckGroup.add(wheelGroup);
    wheels.push(wheelGroup); // 애니메이션 업데이트용 바퀴 그룹 등록
  });

  // 8. 짐(Cargo) 관리 그룹 생성 및 트럭에 장착
  cargoGroup = new THREE.Group();
  cargoGroup.position.set(0, 0.7, -1.9); // 적재함 바닥 높이에 맞춰 배치
  truckGroup.add(cargoGroup);

  // 9. 질량에 기반한 짐 채우기
  updateCargoBoxes(mass);

  scene.add(truckGroup);
}

// --- 질량 값에 따른 적재함 상자들 실시간 구성 ---
function updateCargoBoxes(currentMass) {
  // 기존 적재함 짐 싹 비우기
  while (cargoGroup.children.length > 0) {
    const obj = cargoGroup.children[0];
    cargoGroup.remove(obj);
  }

  // 기본 차량 무게(1000kg) 이상일 때 상자 개수 증가
  // 1000kg: 0개, 5000kg: 16개 상자
  const addedWeight = currentMass - 1000;
  const numBoxes = Math.min(16, Math.floor(addedWeight / 250));

  const boxSize = 0.45;
  const boxGeo = new THREE.BoxGeometry(boxSize, boxSize, boxSize);
  const boxMat = new THREE.MeshStandardMaterial({
    color: 0xcd853f, // 카드보드 갈색
    roughness: 0.9
  });

  // 포장 테이프 데코레이션용 얇은 박스
  const tapeMat = new THREE.MeshStandardMaterial({ color: 0xdeb887, roughness: 0.7 });
  const tapeGeo = new THREE.BoxGeometry(0.08, 0.01, boxSize + 0.01);

  // 최대 16개 박스를 적재함에 쌓을 3차원 슬롯 배정
  // 1층에 최대 8개 (Z: 4열 x X: 2열), 2층에 최대 8개
  const boxSlots = [];

  // 1층 슬롯 (Y = boxSize / 2)
  for (let layer = 0; layer < 2; layer++) {
    const yOffset = (boxSize / 2) + layer * (boxSize + 0.02);
    for (let col = 0; col < 4; col++) {
      const zOffset = 0.9 - col * 0.6; // 적재함 앞(0.9)부터 뒤(-0.9) 방향으로 배치
      for (let row = 0; row < 2; row++) {
        const xOffset = -0.45 + row * 0.9; // 좌(-0.45), 우(0.45) 배치
        boxSlots.push({ x: xOffset, y: yOffset, z: zOffset });
      }
    }
  }

  // 박스 개수만큼 적재함에 상자 메쉬 생성 후 얹기
  for (let i = 0; i < numBoxes; i++) {
    const slot = boxSlots[i];
    const singleBoxGroup = new THREE.Group();
    singleBoxGroup.position.set(slot.x, slot.y, slot.z);

    // 골판지 박스 몸체
    const boxMesh = new THREE.Mesh(boxGeo, boxMat);
    boxMesh.castShadow = true;
    boxMesh.receiveShadow = true;
    singleBoxGroup.add(boxMesh);

    // 택배 테이프 한 줄
    const tapeMesh = new THREE.Mesh(tapeGeo, tapeMat);
    tapeMesh.position.y = boxSize / 2 + 0.005;
    singleBoxGroup.add(tapeMesh);

    // 실감나는 연출을 위해 각도를 살짝씩 삐뚤빼뚤하게 배치
    singleBoxGroup.rotation.y = (Math.random() - 0.5) * 0.12;

    cargoGroup.add(singleBoxGroup);
  }
}

// --- 브레이크등 상태 변경 ---
function setBrakeLightsActive(active) {
  if (active) {
    // 밝게 발광하는 붉은색 테마 적용
    leftBrakeLight.material.color.setHex(0xff0000);
    leftBrakeLight.material.emissive.setHex(0xff0000);
    leftBrakeLight.material.emissiveIntensity = 3.0;

    rightBrakeLight.material.color.setHex(0xff0000);
    rightBrakeLight.material.emissive.setHex(0xff0000);
    rightBrakeLight.material.emissiveIntensity = 3.0;

    // 포인트 라이트로 뒤쪽 바닥을 붉게 밝힘
    brakePointLight.color.setHex(0xff0000);
    brakePointLight.intensity = 4.0;
    brakePointLight.position.set(0, 0.8, truckGroup.position.z - 3.3);
  } else {
    // 끈 상태 (어두운 색상 및 발광 해제)
    leftBrakeLight.material.color.setHex(0x400000);
    leftBrakeLight.material.emissive.setHex(0x000000);
    leftBrakeLight.material.emissiveIntensity = 0;

    rightBrakeLight.material.color.setHex(0x400000);
    rightBrakeLight.material.emissive.setHex(0x000000);
    rightBrakeLight.material.emissiveIntensity = 0;

    brakePointLight.intensity = 0;
  }
}

// --- 카메라 기본 위치 리셋 ---
function resetCamera() {
  truckGroup.position.set(0, 0, START_Z);

  // 3/4 뒷모습 오프셋 적용
  camera.position.copy(truckGroup.position).add(offsetRear);
  controls.enabled = true;
  controls.target.set(0, 0.8, START_Z + 1.5);
  controls.update();
}


// --- 챌린지 모드용 새로운 목표 생성 ---
function generateNewChallenge() {
  if (simulationState !== 'idle' && simulationState !== 'stopped') return;

  // 25m에서 95m 사이의 임의 정수 생성
  targetDistance = Math.floor(Math.random() * (95 - 25 + 1)) + 25;

  // 빨간 목표선 Z 위치 업데이트
  if (redLineMesh) redLineMesh.position.z = targetDistance;
  if (redLineSignpost) redLineSignpost.position.set(10 / 2 + 1.5, 0, targetDistance);

  // 도로 위 노면 글씨 Z 위치 업데이트 (목표 선 직전 배치)
  if (roadText) {
    roadText.position.z = targetDistance - 18.4;
  }

  safeSetText('target-distance-value', targetDistance.toFixed(1));

  // 반투명 목표 거리 모달 팝업 띄우기
  showTargetModal(targetDistance);

  resetSimulation();
}

// --- 반투명 목표 거리 모달 노출 제어 ---
function showTargetModal(dist) {
  const modal = document.getElementById('target-modal');
  const modalText = document.getElementById('modal-target-dist');
  if (modal && modalText) {
    modalText.innerText = dist.toFixed(1);
    modal.style.display = 'flex';
  }
}

function closeTargetModal() {
  const modal = document.getElementById('target-modal');
  if (modal) {
    modal.style.display = 'none';
  }
}

// 전역 스코프에 노출하여 HTML inline onclick에서 호출 가능하게 함
window.closeTargetModal = closeTargetModal;
window.showTargetModal = showTargetModal;

// --- 결과 안내 모달 노출 제어 ---
function showResultModal(actualDist, targetDist, diff, absDiff) {
  const modal = document.getElementById('result-modal');
  const modalTitle = document.getElementById('modal-result-title');
  const modalActual = document.getElementById('modal-actual-dist');
  const modalTarget = document.getElementById('modal-target-dist-result');
  const modalFeedback = document.getElementById('modal-result-feedback');

  if (!modal) return;

  modalActual.innerText = `${actualDist.toFixed(2)}m`;
  modalTarget.innerText = `${targetDist.toFixed(1)}m`;

  if (absDiff <= 0.6) {
    modalFeedback.className = 'result-feedback-box success';
    modalTitle.innerText = '🎯 미션 성공!';
    modalFeedback.innerHTML = `목표 정지선 오차 <strong>${absDiff.toFixed(2)}m</strong> 이내로 <strong>정확히 정차</strong>했습니다!`;
  } else {
    modalFeedback.className = 'result-feedback-box fail';
    if (diff > 0) {
      modalTitle.innerText = '💥 정지선 초과 (오버런)';
      modalFeedback.innerHTML = `목표 정지선보다 <strong>${diff.toFixed(2)}m 지나쳤습니다</strong>.`;
    } else {
      modalTitle.innerText = '⚠️ 제동 거리 미달 (조기 정지)';
      modalFeedback.innerHTML = `목표 정지선에 <strong>${Math.abs(diff).toFixed(2)}m 모자라게 멈췄습니다</strong>.`;
    }
  }

  modal.style.display = 'flex';
}

function closeResultModal() {
  const modal = document.getElementById('result-modal');
  if (modal) {
    modal.style.display = 'none';
  }
}

window.showResultModal = showResultModal;
window.closeResultModal = closeResultModal;

// --- 시뮬레이션 및 입력 UI 동기화 ---
function setupUIEventListeners() {
  const massInput = document.getElementById('mass-input');
  if (massInput) {
    massInput.addEventListener('blur', () => {
      let val = parseInt(massInput.value);
      if (isNaN(val)) val = 1500;
      val = Math.max(1000, Math.min(5000, val));
      massInput.value = val;
      mass = val;
      const massSlider = document.getElementById('mass-slider');
      if (massSlider) massSlider.value = val;
      updateCargoBoxes(mass);
      updateDashboard();
    });
  }
  const speedInput = document.getElementById('speed-input');
  if (speedInput) {
    speedInput.addEventListener('blur', () => {
      let val = parseInt(speedInput.value);
      if (isNaN(val)) val = 50;
      val = Math.max(10, Math.min(150, val));
      speedInput.value = val;
      initialSpeedKmh = val;
      const speedSlider = document.getElementById('speed-slider');
      if (speedSlider) speedSlider.value = val;
      updateDashboard();
    });
  }
}

// --- 대시보드 실시간 정보 갱신 ---
function updateDashboard(currentSpeedValKmh) {
  // 속도값 입력
  const displaySpeed = currentSpeedValKmh !== undefined ? currentSpeedValKmh : initialSpeedKmh;
  const displaySpeedMps = displaySpeed / 3.6;

  // 운동에너지 계산 (E = 0.5 * m * v^2)
  const energyJoules = 0.5 * mass * Math.pow(displaySpeedMps, 2);
  const energyKiloJoules = energyJoules / 1000;

  safeSetText('energy-value', energyKiloJoules.toFixed(1));

  // 운동에너지 그래프 게이지바 업데이트 (1000kg 10km/h 최소 ~ 5000kg 150km/h 최대 대비 비율)
  // 최대 에너지: 0.5 * 5000 * (41.67)^2 = 4,340,277 J (4340 kJ)
  const maxEnergy = 4340;
  const energyPercent = Math.min(100, (energyKiloJoules / maxEnergy) * 100);
  safeSetStyleWidth('energy-bar', `${energyPercent}%`);

  // 상태 배지 업데이트
  const badge = document.getElementById('status-badge');
  if (badge) {
    badge.className = 'status-badge'; // 기본 클래스 리셋

    if (simulationState === 'idle') {
      badge.innerText = '대기 중';
      badge.classList.add('state-idle');
    } else if (simulationState === 'driving') {
      badge.innerText = '가속 주행';
      badge.classList.add('state-driving');
    } else if (simulationState === 'braking') {
      badge.innerText = '제동 감속';
      badge.classList.add('state-braking');
    } else if (simulationState === 'stopped') {
      badge.innerText = '정지 완료';
      badge.classList.add('state-stopped');
    }
  }

  // 실시간 예상 제동 거리 계산 및 반영
  const predDist = (mass * Math.pow(displaySpeed, 2)) / 200000;
  safeSetText('predicted-distance-value', predDist.toFixed(1));
}

// --- 이징(Easing) 함수: 부드러운 카메라 전환용 ---
function easeInOutQuad(t) {
  return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
}

// --- 시뮬레이션 출발 ---
function startSimulation() {
  if (simulationState !== 'idle') return;

  // 출발 버튼 클릭 시 안내 모달 팝업 닫기
  closeTargetModal();

  // 슬라이더 및 입력 상자 조작 불가능하도록 락 걸기
  toggleInputs(true);

  simulationState = 'driving';
  initialSpeedMps = initialSpeedKmh / 3.6;
  currentSpeedMps = initialSpeedMps;
  brakingElapsedTime = 0;

  // 주행 중 사용자가 카메라를 돌려 구도가 깨지는 것을 방지하기 위해 마우스 조작 비활성화
  controls.enabled = false;

  // 버튼들 비활성화 설정
  safeSetDisabled('btn-start', true);
  safeSetDisabled('btn-reset', false);
  safeSetDisabled('btn-new-target', true);

  // 결과 창 리셋
  safeSetStyleDisplay('result-box', 'none');

  // 가상 환경 속도감 재세팅을 위해 시계 리셋
  clock.getDelta();
}

// --- 시뮬레이션 정지 및 원상 복구 ---
function resetSimulation() {
  simulationState = 'idle';
  currentSpeedMps = 0;

  // 결과 안내 모달 팝업 닫기
  closeResultModal();

  // 브레이크등 라이트 소등
  setBrakeLightsActive(false);

  // 대시보드 텍스트 복구
  safeSetText('actual-distance-value', '0.0');
  safeSetStyleDisplay('result-box', 'none');

  // 차량 위치 및 회전 바퀴 리셋
  resetCamera();

  // 컨트롤 락 해제
  toggleInputs(false);

  // 출발 버튼 활성화
  safeSetDisabled('btn-start', false);
  safeSetDisabled('btn-reset', true);
  safeSetDisabled('btn-new-target', false);

  updateDashboard();

  // 초기화 버튼 클릭 시 안내 모달 팝업 다시 띄우기
  showTargetModal(targetDistance);
}

function toggleInputs(disabled) {
  safeSetDisabled('mass-slider', disabled);
  safeSetDisabled('mass-input', disabled);
  safeSetDisabled('speed-slider', disabled);
  safeSetDisabled('speed-input', disabled);
}

// --- 제동 완수 및 결과 판정 ---
function showResults() {
  const finalDistance = truckGroup.position.z + 2.5; // 앞 범퍼(local Z=2.5) 기점으로 제동 거리 환산
  safeSetText('actual-distance-value', finalDistance.toFixed(2));

  // 제동 완료 후 사용자가 차량 근처에서 카메라 조작을 즐길 수 있도록 락 해제 및 타겟 갱신
  controls.target.copy(truckGroup.position).add(new THREE.Vector3(0, 0.8, 1.5));
  controls.enabled = true;
  controls.update();

  // 챌린지 성공 조건 판정 (목표선 대비 오차가 0.6m 이내인지 판단)
  const diff = finalDistance - targetDistance;
  const absDiff = Math.abs(diff);

  const resultBox = document.getElementById('result-box');
  if (resultBox) {
    if (absDiff <= 0.6) {
      resultBox.className = 'result-box success'; // 스타일 시트에 녹색 테두리 반영
      safeSetText('result-title', '🎯 미션 성공!');
      safeSetHTML('result-desc', `목표: ${targetDistance.toFixed(1)}m | 실제 제동: ${finalDistance.toFixed(2)}m<br>오차: <span style="font-weight:700; color:#4caf50;">${diff >= 0 ? '+' : ''}${diff.toFixed(2)}m</span>`);
    } else {
      resultBox.className = 'result-box fail'; // 스타일 시트에 적색 테두리 반영
      if (diff > 0) {
        safeSetText('result-title', '💥 정지선 초과 (오버런)');
        safeSetHTML('result-desc', `목표를 <span style="font-weight:700;">${diff.toFixed(2)}m</span> 초과했습니다.`);
      } else {
        safeSetText('result-title', '⚠️ 제동 거리 미달 (조기 정지)');
        safeSetHTML('result-desc', `목표보다 <span style="font-weight:700;">${Math.abs(diff).toFixed(2)}m</span> 덜 갔습니다.`);
      }
    }
    resultBox.style.display = 'block';
  }

  updateDashboard(0);

  // 결과 안내 팝업 모달 띄우기
  if (isMultiplayer) {
    reportStudentResult(finalDistance, diff);
  } else {
    showResultModal(finalDistance, targetDistance, diff, absDiff);
  }
}

// --- 메인 업데이트 루프 (Three.js 및 물리학 실행) ---
function update() {
  let dt = clock.getDelta();
  if (dt > 0.05) dt = 0.05; // 탭 전환 시 오류 방지용 캡핑

  if (userRole === 'teacher') {
    updateTeacherPhysics(dt);
  } else {
    // 1. 차량 상태별 물리학 프레임 갱신
    if (simulationState === 'driving') {
      // 검은 브레이크선 Z=0을 향해 등속 주행
      truckGroup.position.z += initialSpeedMps * dt;

      // 바퀴 굴러가기
      const wheelRotSpeed = initialSpeedMps / WHEEL_RADIUS;
      wheels.forEach(w => w.rotation.x += wheelRotSpeed * dt);

      // 카메라 3/4 뒷모습에서 90도 옆모습(Side view)으로 부드럽게 스윕
      // 앞 범퍼가 브레이크선(Z=0)에 닿을 때까지(출발지 Z=-30m에서 -2.5m까지 총 27.5m 이동) 비율 progress
      const progress = Math.max(0, Math.min(1, (truckGroup.position.z - START_Z) / (BRAKE_Z - 2.5 - START_Z)));
      const eased = easeInOutQuad(progress);

      // 위치 보간 (컨트롤 락 된 상태이므로 수동 세팅)
      const currentOffset = new THREE.Vector3().lerpVectors(offsetRear, offsetSide, eased);
      camera.position.copy(truckGroup.position).add(currentOffset);

      // 카메라는 차량 중앙 높이를 쳐다봄
      const targetLook = truckGroup.position.clone().add(new THREE.Vector3(0, 0.8, 1.5));
      camera.lookAt(targetLook);

      // 앞 범퍼(local Z=2.5)가 Z=0(브레이크 라인)을 돌파하는 순간 제동 페이즈 전환
      if (truckGroup.position.z + 2.5 >= BRAKE_Z) {
        truckGroup.position.z = BRAKE_Z - 2.5; // 앞 범퍼가 시작선에 정확히 정렬되도록 오차 제거
        simulationState = 'braking';
        setBrakeLightsActive(true);
        updateDashboard();
      }
    }
    else if (simulationState === 'braking') {
      // 제동 페이즈: F = m * a  => a = F_brake / m
      const deceleration = F_BRAKE / mass;
      brakingElapsedTime += dt;

      const t = brakingElapsedTime;
      const stopTime = initialSpeedMps / deceleration;

      if (t >= stopTime) {
        // 완전히 멈춤 (앞 범퍼 기준의 위치 산정)
        truckGroup.position.z = (Math.pow(initialSpeedMps, 2) / (2 * deceleration)) - 2.5;
        currentSpeedMps = 0;
        simulationState = 'stopped';
        showResults();
      } else {
        // 감속 주행 공식: x(t) = v0*t - 0.5*a*t^2 (앞 범퍼 Z=0 기점으로 셋팅)
        truckGroup.position.z = -2.5 + (initialSpeedMps * t) - (0.5 * deceleration * Math.pow(t, 2));
        currentSpeedMps = initialSpeedMps - (deceleration * t);

        // 남은 속도에 맞추어 바퀴 회전 속도도 서서히 정지
        const wheelRotSpeed = currentSpeedMps / WHEEL_RADIUS;
        wheels.forEach(w => w.rotation.x += wheelRotSpeed * dt);

        // 대시보드 실시간 거리 갱신 (제동 거리는 앞 범퍼 위치 Z + 2.5)
        safeSetText('actual-distance-value', (truckGroup.position.z + 2.5).toFixed(2));

        // 실시간 속도 기준으로 대시보드 에너지 갱신
        const currentKmh = currentSpeedMps * 3.6;
        updateDashboard(currentKmh);
      }

      // 제동 구간에서는 계속 고정된 카메라 Side view 유지하며 차량 추적
      camera.position.copy(truckGroup.position).add(offsetSide);

      // 타겟 지점도 부드럽게 추종
      const targetLook = truckGroup.position.clone().add(new THREE.Vector3(0, 0.8, 1.5));
      camera.lookAt(targetLook);

      // 제동등 포인트 조명 위치 갱신
      if (simulationState === 'braking') {
        brakePointLight.position.set(0, 0.8, truckGroup.position.z - 3.3);
      }
    }
    else {
      // IDLE 이나 STOPPED 상태에서는 사용자가 자유롭게 카메라 회전 및 탐색을 즐기게끔 controls만 주기적으로 업데이트
      controls.update();
    }
  }

  // 2. 최종 프레임 렌더링
  renderer.render(scene, camera);
}

// --- 창 크기 대응 반응형 뷰포트 처리 ---
function onWindowResize() {
  const container = document.getElementById('canvas-container');
  camera.aspect = container.clientWidth / container.clientHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(container.clientWidth, container.clientHeight);
}

// --- 교사용 실시간 물리학 프레임 업데이트 ---
function updateTeacherPhysics(dt) {
  if (simulationState === 'idle') {
    controls.update();
    updateStudentNameTags();
    return;
  }

  let allStopped = true;

  activeStudents.forEach((student) => {
    const state = studentReadyStates[student.id] || { mass: 1500, speed: 50 };
    const initialSpeedMps = state.speed / 3.6;
    const deceleration = F_BRAKE / state.mass;

    let curState = studentCarStates[student.id] || 'idle';
    let curZ = studentCarPositions[student.id] !== undefined ? studentCarPositions[student.id] : START_Z;
    let curSpeed = studentCarSpeeds[student.id] !== undefined ? studentCarSpeeds[student.id] : initialSpeedMps;
    let curTime = studentCarTimes[student.id] || 0;

    if (curState === 'driving') {
      allStopped = false;
      curZ += initialSpeedMps * dt;

      if (curZ + 2.5 >= BRAKE_Z) {
        curZ = BRAKE_Z - 2.5;
        curState = 'braking';
        curTime = 0;
      }
    } else if (curState === 'braking') {
      allStopped = false;
      curTime += dt;
      const stopTime = initialSpeedMps / deceleration;

      if (curTime >= stopTime) {
        curZ = (Math.pow(initialSpeedMps, 2) / (2 * deceleration)) - 2.5;
        curSpeed = 0;
        curState = 'stopped';

        // 리더보드 결과 누적
        const finalDistance = curZ + 2.5;
        const offset = finalDistance - targetDistance;
        addStudentResult({
          studentId: student.id,
          nickname: student.nickname,
          mass: state.mass,
          speed: state.speed,
          actualDistance: finalDistance,
          offsetDistance: offset
        });
      } else {
        curZ = -2.5 + (initialSpeedMps * curTime) - (0.5 * deceleration * Math.pow(curTime, 2));
        curSpeed = initialSpeedMps - (deceleration * curTime);
      }
    }

    studentCarStates[student.id] = curState;
    studentCarPositions[student.id] = curZ;
    studentCarSpeeds[student.id] = curSpeed;
    studentCarTimes[student.id] = curTime;
  });

  // 3D 객체 인스턴스 갱신 및 2D 닉네임 꼬리표 갱신
  updateInstancedTrucks();
  updateStudentNameTags();

  // 모든 참여 차량의 평균 Z 위치 계산 (카메라 추적 타겟)
  let totalZ = 0;
  activeStudents.forEach(student => {
    totalZ += studentCarPositions[student.id] !== undefined ? studentCarPositions[student.id] : START_Z;
  });
  const avgZ = activeStudents.length > 0 ? (totalZ / activeStudents.length) : START_Z;

  // 카메라 트래킹 설정
  const roadWidth = activeStudents.length === 1 ? 10 : activeStudents.length * 3.5 + 4;
  const camX = - (roadWidth / 2 + 18);
  const camY = 12;

  if (simulationState === 'driving' || simulationState === 'braking') {
    camera.position.set(camX, camY, avgZ + 5);
    camera.lookAt(new THREE.Vector3(0, 1.5, avgZ));
    controls.target.set(0, 1.5, avgZ);
  } else {
    controls.update();
  }

  // 모든 차량이 멈췄을 때 최종 리더보드로 전환
  if (allStopped && activeStudents.length > 0 && (simulationState === 'driving' || simulationState === 'braking')) {
    simulationState = 'stopped';
    const activeEl = document.getElementById('teacher-active');
    if (activeEl) activeEl.style.display = 'none';
    const lbSection = document.getElementById('teacher-leaderboard-section');
    if (lbSection) lbSection.style.display = 'flex';

    controls.enabled = true;
    controls.target.set(0, 1.5, avgZ);
    controls.update();
  }
}

// --- 사용자 친화적 입력 동기화 헬퍼 함수 ---
function syncInputs(type, value) {
  let val = parseInt(value);
  if (isNaN(val)) return;

  const massSlider = document.getElementById('mass-slider');
  const speedSlider = document.getElementById('speed-slider');

  if (type === 'mass') {
    if (val >= 1000 && val <= 5000) {
      mass = val;
      if (massSlider) massSlider.value = val;
      updateCargoBoxes(mass);
    } else {
      // 타이핑 도중 즉시 잘려 나가는 불쾌감을 없애기 위해 값만 clamped 임시 적용
      mass = Math.max(1000, Math.min(5000, val));
      if (massSlider) massSlider.value = mass;
      updateCargoBoxes(mass);
    }
  } else if (type === 'speed') {
    if (val >= 10 && val <= 150) {
      initialSpeedKmh = val;
      if (speedSlider) speedSlider.value = val;
    } else {
      initialSpeedKmh = Math.max(10, Math.min(150, val));
      if (speedSlider) speedSlider.value = initialSpeedKmh;
    }
  }
  updateDashboard();
}
window.syncInputs = syncInputs;

// --- 안전한 DOM 수정 헬퍼 함수들 ---
function safeSetDisabled(id, disabled) {
  const el = document.getElementById(id);
  if (el) el.disabled = disabled;
}
function safeSetText(id, text) {
  const el = document.getElementById(id);
  if (el) el.innerText = text;
}
function safeSetHTML(id, html) {
  const el = document.getElementById(id);
  if (el) el.innerHTML = html;
}
function safeSetStyleDisplay(id, display) {
  const el = document.getElementById(id);
  if (el) el.style.display = display;
}
function safeSetStyleWidth(id, width) {
  const el = document.getElementById(id);
  if (el) el.style.width = width;
}
function safeSetClass(id, className) {
  const el = document.getElementById(id);
  if (el) el.className = className;
}

// --- 앱 초기 실행 ---
window.onload = () => {
  init();
};
